### ISSUE TITLE
New tabs implementation prohibits use of custom link elements.

### ISSUE THREAD

**Issue by janpieterz** [tleunen/react-mdl#116]
I'm using React-Router, which provides a Link component (a simply wrapper around a, where they provide functionality to route correctly through the app).

The new header tabs implementation prohibits the use of this since it always forces to have a Tab, which prohibits the use of anything else beside an a. 

I'd suggest for Tab using a similar approach to button, where you can provide a component. If this is provided, then this specific component gets rendered, if not, the a.

More than happy to take it on in a pull-request if you agree with the proposal.

**Comment by tleunen** [comment]
What about changing `Tabs` to allow anything, and wrap the children with `Tab`. Instead of rendering a link, `Tab` will render the child with the custom props.

What do you think?

**Comment by janpieterz** [comment]
Good idea, super flexible, but wouldn't this break the just-released version, pushing it over to the next mayor?

**Comment by tleunen** [comment]
I have to merge the babel6 branch in master and it will be a major update as well... I'm surprised nobody complained yet that the available version not compatible with babel 6.

Anyway we could also wrap it only if it's not already a tab ;)

**Comment by janpieterz** [comment]
Somehow I'm running it with babel 6 locally without a problem, so I'm not sure how that works out. It is actually quite weird because I see you used class properties, which don't seem to work in my own code but they do seem to run in yours. Perhaps because it only uses the compiled version which is compiled with babel < 6?

Ah, that seems to be the best way to go then.

**Comment by tleunen** [comment]
Yes indeed. I was completely wrong. Babel is only a dependency for building the code, so that's fine. I can easily merge the babel6 branch without updating the version.

**Comment by tleunen** [comment]
hey @janpieterz, instead of changing the way it work, what do you think of having a prop called `component` allowing you to decide what component to render, with a default to `<a>` (current behavior) ?

We already use this prop for a few other component (Button, Grid, Dialog, ..), so at least we keep it "standard".
