### ISSUE TITLE
The scss file imports missing files

### ISSUE THREAD

**Issue by Pajn** [tleunen/react-mdl#138]
It would be nice if the scss file instead imported from the mdl module so that it could reused.

**Comment by tleunen** [comment]
Do you mean the 2 imports inside the `_layout.scss` file in our extra directory?

**Comment by Pajn** [comment]
Exactly, would be great if they instead were
```
@import "~material-design-lite/src/variables";
@import "~material-design-lite/src/mixins";
```
so one could import the file directly instead of copying it and changing those two imports.

**Comment by ciccia** [comment]
+1
