### ISSUE TITLE
[idea] Use MDL SCSS files instead of compiled CSS ?

### ISSUE THREAD

**Issue by slybridges** [tleunen/react-mdl#14]
Hi,

I've just started playing with `react-mdl` and it looks quite promising !

One question though: as we only have CSS version of the modified MDL styles, I was wondering how best to change the styling, like the `$color-primary`  without going everywhere and replace all occurrences in the compiled CSS?

It would be awesome to have the modified SCSS files in this repo so that we can integrate them directly in our pipeline. SCSS files could be compiled into  `extra/material.css` for those wanting to use CSS directly and for backward compatibility.

**Comment by darkyen** [comment]
+1

**Comment by tleunen** [comment]
Good idea!
I'll add it later today in the repo :)
In the meantime, you can find my only changes in this file https://github.com/google/material-design-lite/pull/1357/files#diff-e8d273098ad170740ae489c057f29e9d

**Comment by tleunen** [comment]
I added the files inside master.
I'll publish a new version on NPM in the next days with the recent changes

**Comment by slybridges** [comment]
Awesome, thanks ! 
I see you only included the modified _layout.scss. Is it safe to pull out other scss files from the master branch of the official mdl repo you think ? Or should I look at a particular revision ?

**Comment by tleunen** [comment]
You should use the ones from the release branch on MDL https://github.com/google/material-design-lite/tree/release

**Comment by slybridges** [comment]
👍🏼
