### ISSUE TITLE
any way to customise color?

### ISSUE THREAD

**Issue by songzijun** [tleunen/react-mdl#145]
thanks for creating react components for mdl. I am interested in using it. But I cannot see a way to customise color. As the cdn version of mdl can specify different color. Is it possible to make the css to work with different color like blur?

**Comment by tleunen** [comment]
Unfortunately if you're using our custom css to fix an issue with the layout, it's not possible to customize the color. I'm trying to find a better solution to this

**Comment by songzijun** [comment]
thanks!

**Comment by jpklzm** [comment]
Any updates about this case?

**Comment by tleunen** [comment]
Not that I'm aware of.. But some people got something in this thread https://github.com/tleunen/react-mdl/issues/148
