### ISSUE TITLE
Add documentation on how to compile your own stylesheets.

### ISSUE THREAD

**Issue by skeskinen** [tleunen/react-mdl#148]
I think there should be short section in readme that describes the setup you need to compile mdl scss files and how to change the primary/accent colors.

This should be really easy way of making the library more useful for newcomers and save them some time. There might be some better long term solution but the setup is quite simple so I think this would be good enough for now?

Something like this (not tested):
```
mkdir mdl-styles
cp node_modules/material-design-lite/src/material-design-lite.scss mdl-styles                   
cp node_modules/material-design-lite/src/_variables.scss mdl-styles                             
cp node_modules/react-mdl/extra/_layout.scss mdl-styles
cd mdl-styles
sed -i 's/@import "/@import "~material-design-lite\/src\//' material-design-lite.scss
sed -i 's/".*variables"/"variables"/' material-design-lite.scss
sed -i 's/".*layout"/"layout"/' material-design-lite.scss
sed -i 's/".*variables"/"variables"/' _layout.scss
sed -i 's/".*mixins"/~material-design-lite\/src\/mixins/' _layout.scss
sed -i 's/@import "/@import "~material-design-lite\/src\//' _variables.scss
sed -i 's/\/images/~material-design-lite\/src\/images/' _variables.scss
```
1. In `_variables.scss` edit color variables to your preferred values: `$color-primary` `$color-primary-dark` `$color-accent` `$color-primary-contrast` `$color-accent-contrast` 
2. Setup webpack sass-loader or other scss compiler.
3. In your project include: `~react-mdl/extra/material.min.js` and `mdl-styles/material-design-lite.scss`

**Comment by tleunen** [comment]
Hmm indeed I think it would be nice to describe the process in the readme. I'm also wondering if it could be possible to use the MDL css and apply a monkey patch on top of it to fix the layout. It might a lot easier for users that way.

**Comment by vmagro** [comment]
I'm also interested in this. It would also be nice for those of us that import all our css with webpack and not have to add another `link` for the mdl stylesheet

**Comment by thomasantony** [comment]
Is there any way at present to dynamically specify the color options from React code?

**Comment by tleunen** [comment]
Nop, there's no way to setup the color from the react component. It's better to setup your styles and then use the component without knowing the color.

**Comment by morlay** [comment]
configure `node_modules/react-mdl` and `node_modules/material-design-lite/src` in to sass's `includePaths[]`

that means
```
// from node_modules/react-mdl
extra/
  _layouts.scss
// from node_modules/material-design-lite/src
layouts/
  _layouts.scss
variables.scss
```
```scss
// index.scss

@import 'extra/_layouts.scss`
```
dirty but works.

**Comment by tleunen** [comment]
Don't hesitate to submit a PR to add the `how to` in the readme.
I also added the complete list of styles in the repo in [/extra/css](https://github.com/tleunen/react-mdl/tree/master/extra/css)
