### ISSUE TITLE
Textfield does not always clear is-invalid when error is set to null or undefined.

### ISSUE THREAD

**Issue by andrepew** [tleunen/react-mdl#152]
Issue exhibited here:

http://jsfiddle.net/jq0Lzgwn/

Click the error link to set an error on the Textfield and then click submit which will try to set error back to null. It succeeds in blanking out the error text but the Textfield still has the is-invalid class.

**Comment by tleunen** [comment]
hey @slybridges, because you made the initial code to force the invalid state in react-mdl, you might know why the classname is not reset.
In the example from @andrepew, it seems MDL doesn't remove the `is-invalid` classname when rendering the textfield. Do you know if they changed something in a recent release?

**Comment by slybridges** [comment]
Hi @tleunen @andrepew - let me have a look

**Comment by slybridges** [comment]
@andrepew was on the right track, this is because `react-mdl`doesn't check for the new validity of a field when error changes.
However I think, we can have a slightly better fix than the one suggested in #151. I'll submit a PR.

**Comment by andrepew** [comment]
IMHO mdl's built-in behaviour of automatically clearing the error on user input is wrong in the context of react. 

It allows for a situation where what the component is displaying is inconsistent with the react property that is set. In the example I gave, this.state.error is still contains 'oops' after the user inputs something. If a developer wants the error to clear on user input, they should have to implement onChange and clear this.state.error via this.setState()

Is it possible to disable mdl's behaviour of auto clearing the error? I'm not very familiar with mdl's JavaScript.
