### ISSUE TITLE
Uncaught TypeError: Cannot read property 'upgradeElement' of undefined

### ISSUE THREAD

**Issue by thomasantony** [tleunen/react-mdl#153]
I have been running a very bare-bones setup with code from the main documentation source (without react-route). I am getting this error in Chrome every single time I run it. 

    Uncaught TypeError: Cannot read property 'upgradeElement' of undefined
      componentDidMount @ MDLComponent.js:31
      assign.notifyAll @ CallbackQueue.js:65
      ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81
      Mixin.closeAll @ Transaction.js:202
      Mixin.perform @ Transaction.js:149
      batchedMountComponentIntoNode @ ReactMount.js:282
      Mixin.perform @ Transaction.js:136
      ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62
      batchedUpdates @ ReactUpdates.js:94
      ReactMount._renderNewRootComponent @ ReactMount.js:476
      wrapper @ ReactPerf.js:66
      ReactMount._renderSubtreeIntoContainer @ ReactMount.js:550
      ReactMount.render @ ReactMount.js:570
      wrapper @ ReactPerf.js:66
      (anonymous function) @ main.js:17
      (anonymous function) @ main.js:19
      (anonymous function) @ main.js:20
      (anonymous function) @ bundle.js:557
      __webpack_require__ @ bundle.js:521
      fn @ bundle.js:76
      (anonymous function) @ multi_main:1
      (anonymous function) @ bundle.js:551
      __webpack_require__ @ bundle.js:521
      (anonymous function) @ bundle.js:544
      (anonymous function) @ bundle.js:547

Also, there is no drawer icon and the whole header disappears if the window is smaller than a certain width. 

Maybe I am missing something fundamental? I did try following the documentation page's source code.

Source code: [minimal-mdl-test.zip](https://github.com/tleunen/react-mdl/files/62094/minimal-mdl-test.zip)

**Comment by thomasantony** [comment]
Nevermind. I wasn't including the material.js file assuming that webpack would take care of it.

**Comment by gillchristian** [comment]
I'm having the same issue, but the material.js file is being included.
Problems is with the `<Drawer>` component

**Comment by tleunen** [comment]
You can add material.js in webpack as well, but since it's not a dependency of react-mdl, you have to do it manually.

See the code on our website as an example: https://github.com/tleunen/react-mdl/blob/master/docs/pages/_template.js#L11

**Comment by gillchristian** [comment]
***Thanks!*** That fixed the error, now it does not show. 

The `<Drawer>` still not showing. But I guess that is not related to the issue.

**Comment by tleunen** [comment]
If you can share some code, maybe I'll be able to help ;)
Otherwise, make sure react renders it. Use the debugger to help you in this task ;) or breakpoints in the code

**Comment by gillchristian** [comment]
That's may code, `<App>` is the main component and `<MainNav>` is for now just a wrapper.
I am seeing everything rendered but the `<Drawer>` as I mentioned.

```jsx
import React from 'react'
import { Layout, Content } from 'react-mdl'
import CategoriesContainer from '../containers/CategoriesContainer'
import MainNav from './MainNav.jsx'

const App = () => (
  <Layout fixedHeader>
    <MainNav/>
    <Content className='centerItem'>
      <div className='wrapper'>
        <CategoriesContainer />
      </div>
    </Content>
  </Layout>
)
export default App
```
```jsx
import React from 'react'
import { Header, Navigation, Drawer } from 'react-mdl'

const MainNav = () => (
  <div>
    <Header title='Wonderassets'>
      <Navigation>
        <a href='#'>Link</a>
      </Navigation>
    </Header>
    <Drawer title='Title'>
      <Navigation>
        <a href='#'>Link</a>
        <a href='#'>Link</a>
        <a href='#'>Link</a>
        <a href='#'>Link</a>
      </Navigation>
    </Drawer>
  </div>
)
export default MainNav
```

**Comment by tleunen** [comment]
I think all the elements inside Layout should be the first child :/

**Comment by gillchristian** [comment]
Yes, looks like that was the problem :grin: 
Glad is solved now :smile: 
BTW `react-mdl` is awesome!

**Comment by tleunen** [comment]
Glad it solves the issue. Thank you :-)

**Comment by drouillard** [comment]
+1 on this issue being helpful. I was seeing weird behavior with ref callbacks not being called. It was due to including the material.js script tag at end of body and with `defer` attribute. Included material.js file properly and my issue cleared up as well.
