### ISSUE TITLE
Textfield should not automatically clear errors set in this.props.error on user input

### ISSUE THREAD

**Issue by andrepew** [tleunen/react-mdl#157]
IMHO mdl's built-in behaviour of automatically clearing the error on user input is wrong in the context of react.

It allows for a situation where what the component is displaying is inconsistent with the react property that is set. In the example jsfiddle I gave in #152 , this.state.error is still contains 'oops' after the user inputs something. If a developer wants the error to clear on user input, they should have to implement onChange and clear this.state.error via this.setState()

Also, this inconsistency breaks the error display behaviour of the component in other ways. For example, all state changes causing a re-render in the parent will cause the Textfield component to flicker between showing and not showing an error if the user enters input between the state changes.

Is it possible to disable mdl's behaviour of auto clearing the error? I'm not very familiar with mdl's JavaScript.

**Comment by slybridges** [comment]
MDL says they're not aiming at supporting dynamic websites (such as those created with React) at the moment. Hence they won't implement solutions using setState and the likes. However I think `react-mdl` plays nicely around those limitations.

I'm using `react-mdl` along with `redux-form` which has some nice helpers to validate the data and display error messages dynamically as you're typing.

Example: http://erikras.github.io/redux-form/#/examples/synchronous-validation

**Comment by tleunen** [comment]
Seems like the expected behavior to me. If the error contains something, it's normal the textfield is still in an invalid state.
