### ISSUE TITLE
Add partial dependences in each component

### ISSUE THREAD

**Issue by morlay** [tleunen/react-mdl#158]
Just created a CommonJS version https://github.com/morlay/material-design-lite-cjs
which will automatic transform origin material-design-lite

``` js
// componentHandler will be loaded too, by the dependence chain
// MaterialButton exported 
// however in this material-design-lite version may not be used directly.
import { MaterialButton } from  'material-design-lite-cjs/src/button'

class Button extends React.Component {
   ...
}
```

* For user who want to partial import, this will be more easier.
* And for some hot fix in React, will be easy to use a partial file to replace in this project.

Hope this is helpful.

**Comment by tleunen** [comment]
Very interesting. Indeed, it's great if you only use a specific component!
But currently, because of the "small" change we have to make on the layout component, using this would be complicated.

> Notice: only component js, sass and polyfill need to import from origin one;

What does it mean?

**Comment by morlay** [comment]
https://github.com/morlay/material-design-lite-cjs/blob/master/index.js

```js
exports['MaterialButton'] = require('./src/button')['MaterialButton'];
exports['MaterialCheckbox'] = require('./src/checkbox')['MaterialCheckbox'];
exports['MaterialDataTable'] = require('./src/data-table')['MaterialDataTable'];
exports['MaterialIconToggle'] = require('./src/icon-toggle')['MaterialIconToggle'];
exports['MaterialLayout'] = require('./src/layout')['MaterialLayout'];
exports['componentHandler'] = require('./src/mdlComponentHandler')['componentHandler'];
exports['MaterialMenu'] = require('./src/menu')['MaterialMenu'];
exports['MaterialProgress'] = require('./src/progress')['MaterialProgress'];
exports['MaterialRadio'] = require('./src/radio')['MaterialRadio'];
exports['MaterialRipple'] = require('./src/ripple')['MaterialRipple'];
exports['MaterialSlider'] = require('./src/slider')['MaterialSlider'];
exports['MaterialSpinner'] = require('./src/spinner')['MaterialSpinner'];
exports['MaterialSwitch'] = require('./src/switch')['MaterialSwitch'];
exports['MaterialTabs'] = require('./src/tabs')['MaterialTabs'];
exports['MaterialTextfield'] = require('./src/textfield')['MaterialTextfield'];
exports['MaterialTooltip'] = require('./src/tooltip')['MaterialTooltip'];
```
in my build, i only process these files,
and in origin one, they have this file https://github.com/google/material-design-lite/blob/master/src/third_party/rAF.js as polyfill.

by the way, in server render, 
have to add the dirty code. :-(
```js
// mdl mock
global.addEventListener = ()=> {
};
```

**Comment by morlay** [comment]
Seems componentHandler is not necessary. Life cycle in React can replace it.
And we could make the export effects as component too.

How do you think this way？

```js
<RippleEffect>
    <Button></Button>
</RippleEffect>
```

```js
// RippleEffect

import { Children, cloneElement } from 'react';
import { MaterialRipple } from 'material-design-lite-cjs/src/ripple';

import connectMDL from './utils/connectMDL';

const RippleEffect = (props) => {
  return cloneElement(Children.only(props.children), {
    className: 'mdl-js-ripple-effect'
  });
};
export default connectMDL(MaterialRipple)(RippleEffect);

```
```js
// Button
import { MaterialButton } from 'material-design-lite-cjs/src/button';
import connectMDL from './utils/connectMDL';
const Button = (props) => {
     // ripple is not need to config in the pure button
     const { accent, className, colored,
      primary, raised, component, href,
      children, ...otherProps } = props;
    
    // mdl-js-button is for componentHandler, once we not depend it, we can remove this className.
    const buttonClasses = classNames('mdl-button', {
      'mdl-button--raised': raised,
      'mdl-button--colored': colored,
      'mdl-button--primary': primary,
      'mdl-button--accent': accent
    }, className);

    return React.createElement(component || (href ? 'a' : 'button'), {
      className: buttonClasses,
      href,
      ...otherProps
    }, children);
}
export default connectMDL(MaterialButton)(Button);
```

```js
// connectMDL
import React, { Component } from 'react';
import { findDOMNode } from 'react-dom';
export default function connectMDL(MaterialClass) {
  return (ReactComponent) => {
    return class MDLComponent extends Component {
      componentDidMount() {
        this._materialInstance = new MaterialClass(findDOMNode(this));
      }
      componentWillUnmount() {
        this._materialInstance.mdlDowngrade();
      }
      render() {
        return <ReactComponent {...this.props}/>;
      }
    };
  };
}
```

**Comment by tleunen** [comment]
I think it's a lot easier to use a `ripple` prop than having a component for that.
The component will not add any value.

**Comment by morlay** [comment]
Just want to split the dependences.

Keep the props `ripple`, we still could did this.
```
MaterialRipple  → RippleEffect ( may just simple function )
                                    →  Button (base MaterialButton)
                                    →  IconToggle (base MaterialIconToggle)                            
```
( After for maintenance works in some big company, I really fear the global dependences, sorry for this :-)

```
MaterialRipple  → RippleEffect
CustomMaterialRipple  → CustomRippleEffect
MaterialIconToggle  → IconToggle
MaterialButton  → Button 
```
Then could let user to composed, and let user could make custom effect as a pure wrapper.

In real project. we usually make some common component instead configure everywhere. so I think this will not different for usage.
```
RippleEffect(Button(raised, colored, primary)) → PrimaryButton
RippleEffect(Button(raised, colored)) → SecondaryButton
```

**Comment by tleunen** [comment]
I understand the need of getting the dependencies instead of using the global MDL. Trust me, I would definitely prefer having a commonjs module that I could use for that :)
And I really like what you did with your package. But for now because of our custom "layout", we cannot use it.

**Comment by morlay** [comment]
Sorry, I haven't got this point. 
In commonjs may be easier to overwrite the official MDL.

```js
import { MaterialLayout } from 'material-design-lite-cjs/src/layout';

MaterialLayout.prototype.CssClasses_.INNER_CONTAINER = 'mdl-layout__inner-container';

MaterialLayout.prototype.init = function (){}

export {
  MaterialLayout
}
```

```
import { MaterialLayout } from './customs/MaterialLayout';
import connectMDL from './utils/connectMDL';

const Layout = (props) => {}

export default connectMDL(MaterialLayout)(Layout);
```

**Comment by tleunen** [comment]
Indeed...
I'll be quite busy during the christmas holidays but I'll try to make something based on your commonjs lib :)

**Comment by morlay** [comment]
Marry Christmas. ~
And once official provide the UMD version in 2.0, my package could delete.

**Comment by tleunen** [comment]
hey @morlay, sorry for the huge delay :/
Could you submit a PR with a component as en example? I think it will allow me to better see and understand the changes and how it will improve the code.

**Comment by morlay** [comment]
After talking with the mdl team, https://github.com/google/material-design-lite/issues/2028
I'm persuaded following the react way to create these components, https://github.com/morlay/react-pure-mdl/
It is already used in my recent project, most of them works well. 
But still need more testings and docs, if I have enough time.

And in the next big version of mdl, there will be a standard way for `component.js` https://github.com/google/material-design-lite/issues/1820.
Maybe just prepare the new version and let this issue closed.

**Comment by tleunen** [comment]
Yep, I was thinking of updating all components to not use their JS at all and just their CSS. I noticed the limitation of using their code when building the snackbar.

Nice work. What do you think of focusing our effort? We could prepare the v2 in a new branch using only the css directly imported in the component using [css modules](https://github.com/css-modules/css-modules)

**Comment by morlay** [comment]
I like `css-modules`, however,  `css-modules` is not fully compatible with `BEM`.
And in the MDL, there are some dirty overwrites crossing components. That means we have to rewrite some css too, if we use css-modules. And http://react-toolbox.com/ which is created by css-modules, is good enough ( There are too may choices in frontend :-P ).

So I think we have to use constants to maintain the classNames like https://github.com/morlay/react-pure-mdl/blob/master/src/cards/constants/CardCssClasses.js

It is `react-mdl`, may just keep rules of the MDL. 

And Google prefer to use some unstable features, even broken in their Chrome, https://github.com/google/material-design-icons/issues/186.
So I feel we should make the composed component easy to replace for user to write their fallbacks ( like the `Icon` in `LayoutHeader` ) .

**Comment by tleunen** [comment]
Could we discuss about it on [discord](https://discord.gg/0ZcbPKXt5bWTpxL5) or somewhere else? :)
