### ISSUE TITLE
Tabs: Improvement Suggestions

### ISSUE THREAD

**Issue by slybridges** [tleunen/react-mdl#159]
:wave: @tleunen 

I am working with some Tabs at the moment and would like to suggest 2 improvement suggestions. 
Happy to make PR(s) if you agree with these.

#### 1/ Allow to style `TabBar`
I would prefer my Tabs to be aligned to the left (vs center by default with `mdl`).
Hence i would need to be able pass some styles to `TabBar` from the `Tabs` component (`justifyCenter: 'left'` in my case)
Are you happy to either pass the `style` prop from `Tabs` to `TabBar` or to add an optional `tabBarStyle` to `Tabs`and pass it down (maybe better)?

#### 2/ Allow Tabs to have only one Tab
In my app, a user that is logged out sees only 1 Tab but 3 if he's logged in.
When there is only 1 Tab,  `react-mdl`throws a warning because it is expecting an `arrayOf` Tabs. Are you happy for me to tweak the PropTypes definition to suppress that warning ? I am thinking of something along the lines of `oneOfType([oneOf(...), arrayOf(...)])`

Cheers

**Comment by tleunen** [comment]
Hmm it's a tricky question. Because we can't really use the style/props from Tabs for TabBar because if we do so, we won't have any way to customize the `mdl-tabs` element.
What about a `tabBarProps` so the end users can easily send whatever he wants?

+1 for the updated PropType to allow a single element.

**Comment by slybridges** [comment]
`tabBarProps`:+1:, much better
I'll get to it.

**Comment by slybridges** [comment]
For the record, if anybody wants to align tabs to the left instead of center, they should add the following prop to Tabs:
```javascript
tabBarProps={{ style: { justifyContent: 'flex-start' } }}
```
