### ISSUE TITLE
React is not defined at http://tleunen.github.io/react-mdl/

### ISSUE THREAD

**Issue by QuantumInformation** [tleunen/react-mdl#166]
There is an error with the doc pages: http://tleunen.github.io/react-mdl/

**Comment by tleunen** [comment]
Could you explain? I don't see any errors.

**Comment by QuantumInformation** [comment]
sure, all I see is:

![image](https://cloud.githubusercontent.com/assets/216566/11977392/3f51bc70-a97a-11e5-9bc4-2880e8d855ce.png)

**Comment by QuantumInformation** [comment]
Closing as facebook.com is blocked, I will try again when its not blocked.

**Comment by tleunen** [comment]
Indeed, if fb.me is blocked, the script won't load. I'll update the link to use another cdn instead.
I'm reopening the ticket as a reminder.
