### ISSUE TITLE
Radio not working in Chrome

### ISSUE THREAD

**Issue by Gregoor** [tleunen/react-mdl#180]
Neither in the docs (http://tleunen.github.io/react-mdl/#/toggles) nor does it work for me locally. Tested in Chrome, without extensions.

Strangely enough it seems to work in FF and Edge.

**Comment by tleunen** [comment]
Good catch. This is because of the empty `onChange` callback.
Either you have to get the changed value and apply it on the radio, or you can get the value with another way (using ref for example) and in that case you don't need the callback.
I'll fix the doc.

**Comment by Gregoor** [comment]
Thanks for getting back to me so quickly (also big thanks for the library, my HTML looks so much better without all those mdl-classes :) ).

I noticed that the change is happening in the underlying input elements, the MDL classes are just not updated. If that's also what you're talking about would I then have to fix the MDL classes when changes happen?

**Comment by tleunen** [comment]
the mdl class `is-checked` should be updated even if you don't specify the change callback. But it will result in the small warning explained in this PR https://github.com/tleunen/react-mdl/pull/181
