### ISSUE TITLE
Support starting and stopping the Spinner

### ISSUE THREAD

**Issue by kretz** [tleunen/react-mdl#189]
The Spinner has start() and stop() methods in Material Design Lite, which in turn control the 'is-active' class on it. 

In react-mdl the class `is-active` is on by default and cannot be changed.

I propose a feature to be able to control the spinner with a property, e.g. `isActive` or `active`.

Thanks,
Martin

**Comment by tleunen** [comment]
@kretz I remember now why I didn't implement it this way in react-mdl. This is because, when the spinner is stopped, it gets invisible. Therefore, in React, you can easily remove it from your render function when you don't want it.

**Comment by kretz** [comment]
Right, that is how I do it today.

BUT what I also found was that if this spinner is taller than the other
elements in a parent element, then the height of the parent element changes
on removal, but not on hiding.

So, I still think there is a case for start and stop. Are you open for a
pull request with this functionality?

**Comment by tleunen** [comment]
Hmm.. Indeed. But usually, a spinner/loader is often put in absolute position in the center of the page, or inside a button after a user interaction. It's rarely always in the page waiting for a loading.

I understand your case though, and of course you can open a PR with the functionality. The active state should be enabled by default though.
