### ISSUE TITLE
Feauture Request: File input button

### ISSUE THREAD

**Issue by odewahn** [tleunen/react-mdl#195]
First off, thanks for this great project.  It really makes MDL super fun to use!

One request: could you add a file upload / select option?

Thanks!

**Comment by tleunen** [comment]
Thanks @odewahn. But this is just a wrapper for MDL. So any feature requests should be on the MDL upstream repository https://github.com/google/material-design-lite
I found this issue mentioning it, but nothing ready yet https://github.com/google/material-design-lite/issues/1031
