### ISSUE TITLE
Add in Sass loading for better file structure

### ISSUE THREAD

**Issue by michaelguild13** [tleunen/react-mdl#196]
https://christianalfoni.github.io/react-webpack-cookbook/Loading-LESS-or-SASS.html

EX: https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/components/InfoBar

I would fork and do it myself but I am already doing it on a private repo for a client.
This is more of a suggestion for future builds

**Comment by tleunen** [comment]
How do you see this with the current MDL dependency? It would be very hard to do so.

**Comment by tleunen** [comment]
Once the MDL lib is completely modular (for both JS and css), this is something we'll implement. Until then, it's not something we can really do.
