### ISSUE TITLE
Add support for valueLink

### ISSUE THREAD

**Issue by aaugustin** [tleunen/react-mdl#198]
It would be pretty cool if:

    <Textfield valueLink={valueLink} />

behaved like:

    <input type="text" valueLink={valueLink} />

Currently, this almost works because a `valueLink` is passed unchanged to the underlying `<input>`, like `value` and `onChange`.

However the `componentDidUpdate` method of `Textfield` uses `this.props.value` directly and thus doesn't update the widget correctly changes when `valueLink` is used.

To account for `valueLink` you need something along these lines:

```javascript
    // assuming you need both value and onChange...
    var {valueLink, value, onChange} = this.props;
    if (valueLink) {
        value = valueLink.value;
        onChange = (event) => valueLink.requestChange(event.target.value);
    }
```

Cf. https://facebook.github.io/react/docs/two-way-binding-helpers.html#reactlink-without-valuelink

A search for `value` and `onChange` in the repository suggests that ten components may need changes if you decide to support `valueLink`.

**Comment by tleunen** [comment]
Hmm.. This is based on a mixin, which is deprecated. So I don't think I'll spend the time to support it. (https://github.com/facebook/react/issues/2302) 

If you specify a valueLink, you don't specify a value. So I'm not sure to see the problem in `componentDidUpdate`.

**Comment by aaugustin** [comment]
Ah, sorry, while the documentation states that `LinkState` mixin is deprecated (like all other mixins), it wasn't it wasn't clear to me what `valueLink` was also deprecated.

I looked at [the code](https://github.com/facebook/react/blob/fdd7fabd129b573fc142df6883398c1ecf0561b0/src/renderers/dom/client/wrappers/ReactDOMInput.js#L93) and indeed it is.

**Comment by aaugustin** [comment]
(For completeness, the problem in `componentDidUpdate` is that, when `this.props.valueLink.value !== prevProps.value`, the block that deals with value changes isn't executed because `this.props.value !== prevProps.value` evaluates to `false` -- both are `undefined`.)

**Comment by tleunen** [comment]
But the condition is there only when the field is updated programmatically (not when the user write directly inside)... I'm not sure to see how this could be related to `valueLink`.

**Comment by aaugustin** [comment]
I noticed this because I was updating the value programatically — not a typical use case, obviously — and passing it through the `valueLink`.

**Comment by tleunen** [comment]
Oh ok, it makes sense now ;)
