### ISSUE TITLE
Add better documentation/example website

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#2]

**Comment by darkyen** [comment]
I would like to contribute in any way possible.

**Comment by tleunen** [comment]
By using it, you already contribute because you might encounter some issues or have new suggestions to improve the library so thanks for that ;)

About the doc, I was thinking of something quite similar to the official doc, (based on this page http://www.getmdl.io/components/index.html) to list the components, show examples with code.

I'd built it based on react-mdl so at the same time it's a good example.

**Comment by darkyen** [comment]
I see you have started the docs in a branch, can you create a roadmap maybe ?

**Comment by tleunen** [comment]
Indeed I started a new branch while it's still in progress. Every day I try to convert the demos into the newly doc website ;)

**Comment by cadesalaberry** [comment]
Forgive my ignorance, but how can you have access to the docs ?

I looked into the docs fork, but the `index.html` file in the **docs** folder leads to nothing...

**Comment by tleunen** [comment]
There's aa build step to create everything. I changed ab bit the structure recently and all the docs are now written in markdown. See this https://github.com/tleunen/react-mdl/tree/docs/docs/pages

**Comment by skaapgif** [comment]
The new docs have proven helpful already, thanks. There's one mistake, on the cards page cards have the following property: `shadowLevel={0}`, from the source code it seems like `shadow` is the correct property or is this a new api?

**Comment by tleunen** [comment]
Good point. The new prop is `shadow` yes. It has been renamed in the v1.

**Comment by cadesalaberry** [comment]
Thanks @tleunen ! Much appreciated.

Wouldn't it make sense now to move everything to the github wiki of this repo, and get rid of the **docs** fork ?

**Comment by tleunen** [comment]
It will be deployed

**Comment by tleunen** [comment]
It will be deployed on the github page to create the React MDL documentation website. It should be done over the weekend now ;)

**Comment by tleunen** [comment]
Here it is, in its first version :) http://tleunen.github.io/react-mdl/
