### ISSUE TITLE
NPM package is broken when installing from a github url

### ISSUE THREAD

**Issue by web2style** [tleunen/react-mdl#20]
Installed the package via npm. When trying to import it:

```
import { Button } from 'react-mdl';
```
I get the following errors:

```
ERROR in ./~/react-mdl/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Spinner in G:\findx\node_modules\react-mdl
 @ ./~/react-mdl/index.js 42:13-37

ERROR in ./~/react-mdl/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Switch in G:\findx\node_modules\react-mdl
 @ ./~/react-mdl/index.js 43:12-35

ERROR in ./~/react-mdl/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Textfield in G:\findx\node_modules\react-mdl
 @ ./~/react-mdl/index.js 46:15-41

ERROR in ./~/react-mdl/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Tooltip in G:\findx\node_modules\react-mdl
 @ ./~/react-mdl/index.js 47:13-37
```

There's no `lib` folder in the package directory:

![screenshot_1](https://cloud.githubusercontent.com/assets/2179726/9519973/37e08eea-4ccc-11e5-9f2b-65c3aa4a7bcd.png)

**Comment by tleunen** [comment]
The lib folder is missing your your hierarchy.. That's weird! I'll take a look.

**Comment by tleunen** [comment]
Not sure why you end up without the lib folder, but have you tried a clean install?
On my side, it seems to work fine.
<img width="644" alt="screen shot 2015-08-27 at 9 28 20 am" src="https://cloud.githubusercontent.com/assets/1972567/9521655/1723517a-4c9e-11e5-926b-4608b8be1854.png">

**Comment by web2style** [comment]
Maybe the problem occurs because I install the package from my fork at github:

```
"react-mdl": "git://github.com/web2style/react-mdl.git#master",
```

And I can't try to install it from npm because it's version doesn't include my pull request (yet, I think) because of react version conflict.

**Comment by darkyen** [comment]
@web2style  do yo run the buildscript after you install ?

**Comment by web2style** [comment]
No. There's nothing about it in the README.

**Comment by tleunen** [comment]
Because you're getting the files from github, you actually don't have the compiled files. Therefore, you have to compile the files yourself with `npm run compile` in the react-mdl directory.

The compiled files are only pushed on NPM when a new version is published.

**Comment by web2style** [comment]
When installing from github, there's no `src` directory either. So `npm run compile` returns `src doesn't exist` error.

**Comment by tleunen** [comment]
Hmm.. Not sure how to fix this thing. Maybe someone has an idea?
I don't want to put the src folder on npm, but because of that it doesn't seem to get fetched when we install it from a github url.

I'll reopen, maybe someone can help here.

**Comment by darkyen** [comment]
How about registering a browserify transform ?! So that browserify compiles
this from src ? (For gh purposes only)

**Comment by slybridges** [comment]
Any reason why you don't want to include the sources on NPM @tleunen ? 
I actually find it's easier to have the sources when investigating a potential bug or wanting to fiddle around with the libs.
And MDL team actually ended including the sources in their NPM because of most people asking for it.
https://github.com/google/material-design-lite/issues/793

**Comment by tleunen** [comment]
The end user cannot do anything with the source since it needs a compilation step. So I was thinking to remove it from npm, but if it's the only solution to get the src folder when installing from github, I guess I'd remove it from the ignore file

**Comment by slybridges** [comment]
As long as the `README` mentions that compiled components are in `lib` and that compenents can be recompiled with `npm install && npm run compile`, it shouldn't be a problem I'd say.
