### ISSUE TITLE
Dialog container must be a child of <body>

### ISSUE THREAD

**Issue by kuy** [tleunen/react-mdl#218]
I just tried out recently implemented Dialog component in my app. It seemingly looks fine, but I found a problem that are no backdrop and incorrect position of the dialog. According to [MDL document](http://www.getmdl.io/components/index.html#dialog-section), a Dialog container must be a child of `<body>` element.

In my React app, it's difficult to render into `<body>` element because I already used a single container for the app's root as a child of `<body>` element. If my problem is caused by that a Dialog container isn't a directly child of `<body>` element, is there solution to avoid this?

**Comment by tleunen** [comment]
Are you using our "un-released" `Dialog` component?
I'm not sure to understand why your dialog is not inside your React app.

Anyway, even if it's separated, why can't you do something like this?
```html
<body>
    <div id="app"></div>
    <dialog>Hi!</dialog>
</body>
```

**Comment by kuy** [comment]
Thanks for your reply!
Yes, I'm using un-released `Dialog` component.
Because I'm using `react-mdl` with Redux, if I put a dialog outside of the root element (in Redux, it's called **container** component), it will be out-of-control. I can put a dialog component as a pure React component, but I can't show/hide it from Redux because it isn't **connected** to Redux's `<Provider>`.

**Comment by tleunen** [comment]
Why would it be out of control? You can pass the `open` prop to the dialog which will open it when needed.

**Comment by kuy** [comment]
Ah...you means I can still set `open` property of `<dialog>` element via DOM interface or call `showModal()` via [JavaScript API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement).

**Comment by kuy** [comment]
@tleunen Sorry for boring you by my question. Finally, I got what I wanted. Using [react-portal](https://github.com/tajo/react-portal), I can put `<Dialog>` component under Redux's rendering tree with placing `<dialog>` tag as a child of `<body>` tag.

Why I want to keep `<Dialog>` component in Redux's rendering tree is that I want to pass a content for the dialog and receive events from the dialog in manner of React.

Thanks for working on `react-mdl`.

**Comment by tleunen** [comment]
Well.. I still don't understand the problem with our [Dialog component](https://github.com/tleunen/react-mdl/tree/master/src/Dialog).

Good thing you found a solution though.
