### ISSUE TITLE
Improve the DataTable component 

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#219]
Some discussions already occurred in #105, but I'd like to recap everything here so it's easier to track.

Here are a few things have in mind
- [x] Move back the `selectable` prop inside the `DataTable`, and also add `onSelectionChanged` and `selectedRows`
- [x] Create a specific component for `TableColumn` with props (`name`, `numeric`, `tooltip`, `cellFormatter`).
- [x] Adds a Sortable table
- [x] Fix the selected rows when the table receives new props
- [x] Write tests

The usage of a specific TableColumn, or the columns prop on the table will result in the exact same result. With a real component, it will be easier to set a specific styles, or width, or even to know if the props are valid.

The target is to keep compatibility with the current implementation as well.

cc @janpieterz @FoxxMD

**Comment by janpieterz** [comment]
Sweet proposal! Sorry, I've been a bit off of projects using MDL lately.

**Comment by tleunen** [comment]
I started the modifications. I didn't push it yet. I'm still thinking about how to build the Sortable thing. If I do a prop, or a HoC component over the current table component.
I'm almost sure I'll go with the HoC component, so I can keep the "sortable state" out of the current component.

**Comment by FoxxMD** [comment]
+1 for HoC. I don't know how you are writing the sortable functionality but providing a way to override your default functionality (per-column?) would be super helpful if the data was more complex than a plain value.

**Comment by tleunen** [comment]
I did something, I still have to adjust the tests.
Basically, I created a new component called `SortableTable` which takes exactly the same props as the default Table, and we can specify a custom `sortFn` on the table headers.

**Comment by FoxxMD** [comment]
perfect

**Comment by michaelguild13** [comment]
Should this just be a prop option for the datatable vs a new component? That's what we're doing for our component library at Inova. Just a thought, not trying to argue anything. You know your repo better than I :)

**Comment by tleunen** [comment]
At first I did it like that, but it also adds a lot of state management in the base table component and I think it's better in this case to have it in another component.

But I agree, because `selectable` is a prop, maybe it would be more consistent to have `sortable` as a prop :/

**Comment by michaelguild13** [comment]
For our component library with MDL, we bounced back and forth with that same problem. I think that's an architectural problem that get's ironed out with maturity. Really, depends on the masses here vs for us, private. I've been enjoying this repo with comparison on how we are doing it here, at Inova. Either way, great work @tleunen

**Comment by tleunen** [comment]
I'm having an issue with the Selectable feature...

When the component receives new props, with new rows.. How should behave the selection? Should we reset everything all the time? It's probably a bad idea, but at the same time, I cannot really know if the row is fully new or not since I only store its id :s I may need to store everything after all :/

**Comment by zeskysee** [comment]
I would like to check whether the following improvement will support custom header that required colSpan as the screenshot below?

<img width="1040" alt="screen shot 2016-03-10 at 10 35 29 pm" src="https://cloud.githubusercontent.com/assets/6244226/13672637/a52b24ea-e710-11e5-9f4f-6a8a8cc0a23e.png">

**Comment by tleunen** [comment]
@zeskysee you mean the row with the "add" and "remove" buttons?
Nop, it won't be part of the table at this stage. But I'm pretty sure you could easily build it outside of it.

**Comment by zeskysee** [comment]
<img width="1040" alt="screen shot 2016-03-10 at 10 35 29 pm" src="https://cloud.githubusercontent.com/assets/6244226/13673260/39cb1fa4-e713-11e5-8f1e-be999d0dcf69.png">

@tleunen so you mean add the buttons outside the table?

**Comment by tleunen** [comment]
Yep, with the new component (not released yet), you'll be able to get the selected rows so you can enable/disable the buttons outside of the table

**Comment by zeskysee** [comment]
May I know will the new data table (not released yet) will be working if i did not specify any table header?

**Comment by tleunen** [comment]
It won't work without headers. Headers are used to know in which order the data have to be displayed.

**Comment by zeskysee** [comment]
After re-read the material design's data tables guideline, it is correct to make the assumption that the header is mandatory
> A data table contains a header row at the top that lists column names, followed by rows for data.

Sorry for my ignorance question. Thanks for the quick response and answer :) Looking forward to your new release data table.

**Comment by tleunen** [comment]
Hopefully, it should be this weekend :)

**Comment by tleunen** [comment]
@michaelguild13 I've decided to change the way I was thinking it. So in my latest attempt, both the `selectable` and `sortable` are props. And I also put the specific code in each a `Selectable` and `Sortable` HoC component so I can keep the initial `Table` component quite easy to read.

No changes for the end user except now when importing the Table, he will both import the sortable/selectable code, even if he never uses them. But I guess that's ok...

**Comment by tleunen** [comment]
PR merged. Closing this ticket
