### ISSUE TITLE
CSS for mdl-1.1.1 components missing

### ISSUE THREAD

**Issue by rimaudev** [tleunen/react-mdl#220]
MDL 1.1.1 [list component](http://www.getmdl.io/components/#lists-section) does not align properly because the required CSS styles are missing.

A workaround is to include original 1.1.1's css before the extra css. 

Hope you can update this soon. Thanks!

**Comment by tleunen** [comment]
What do you mean? Everything looks fine here http://tleunen.github.io/react-mdl/#/lists

**Comment by rimaudev** [comment]
I just realized i was on react-mdl 1.3.0 (that supports mdl 1.0.6). My mistake, will close this ticket.

Thanks for the quick feedback.
