### ISSUE TITLE
Docs don't seem to work on Firefox

### ISSUE THREAD

**Issue by aaugustin** [tleunen/react-mdl#223]
<img width="864" alt="screen shot 2016-02-19 at 15 06 08" src="https://cloud.githubusercontent.com/assets/788910/13177577/5c78479c-d71a-11e5-91d2-4aa193c6d9e7.png">

**Comment by tleunen** [comment]
Hmm... I don't see any issues on FF 44.0.2

**Comment by aaugustin** [comment]
I'm on 44.0.2 as well and the problem persists after restarting Firefox and force-refreshing :-/

It works in Chrome and Safari. Not sure what's going on.

**Comment by tleunen** [comment]
Do you have another machine you could use to test?

**Comment by aaugustin** [comment]
It works on my wife's laptop. Hmpf.

**Comment by aaugustin** [comment]
Ugh, it was Privacy Badger being overzealous and blocking npmcdn.com. Really sorry for the noise!
