### ISSUE TITLE
Snackbar onTimeout still fires after component unmounted

### ISSUE THREAD

**Issue by carpie** [tleunen/react-mdl#226]
I was using the new Snackbar as a means to put up an error message if a user was trying to save my form but still had validation issues.  In the case that the error popped up and the user canceled the edit (thus going to a different page) before the Snackbar disappeared, I ended up getting React warnings because the Snackbar was setting state when the onTimeout timer fired after the unmount.

I believe the fix is as simple as clearing the timeout timer on unmount.  I will send a pull request with this implemented for your review.

**Comment by tleunen** [comment]
Good catch. Indeed, we should clean everything when unmounting the component.

There's another small chance to have an error, with the second timer in the `clearTimeout`. The timer is so small the chances are really low, but still we should clear it.

**Comment by carpie** [comment]
Ah, I see.  If unmount happens while the animation timer is running.  Will do.
