### ISSUE TITLE
clean install causes error with upgradeElement

### ISSUE THREAD

**Issue by swarajd** [tleunen/react-mdl#234]
installing it for the first time and including all the scripts and css from material design lite from their website causes this error: "Uncaught TypeError: Cannot read property 'upgradeElement' of undefined"

edit: this was when attempting to use react-slingshot, and creating a component with a layout with a fixed header.

**Comment by tleunen** [comment]
Are you sure you include either the official mdl js file or the one we provide in /extra?

**Comment by swarajd** [comment]
Ah my mistake I forgot to include the one provided in /extra. Apologies for the mix up
