### ISSUE TITLE
ie 11  not supported method from of Array

### ISSUE THREAD

**Issue by dark4eg** [tleunen/react-mdl#236]
import React from 'react';
import { findDOMNode } from 'react-dom';

/* eslint no-eval: 0 */
export default (html) =>
    class PageComponent extends React.Component {
        componentDidMount() {
            window.componentHandler.upgradeElements(findDOMNode(this));

            const demoJs = document.querySelectorAll('.demo-js');
            Array.from(demoJs).forEach(code => eval(code.innerHTML));

            const dialogs = document.querySelectorAll('dialog');
            [].slice.call(dialogs).forEach(dialog => window.dialogPolyfill.registerDialog(dialog));
        }

        componentWillUnmount() {
            window.componentHandler.downgradeElements(findDOMNode(this));
        }

        render() {
            return <section dangerouslySetInnerHTML={{ __html: html }} />;
        }
    };

/** WEBPACK FOOTER **
 ** ./docs/src/PageComponentHelper.js
 **/

docs/src/PageComponentHelper.js line 11

**Comment by Permagate** [comment]
Based on [https://babeljs.io/docs/learn-es2015/#math-number-string-object-apis](https://babeljs.io/docs/learn-es2015/#math-number-string-object-apis), we might need to include polyfill to support `Array.from` syntax. Or we can just avoid it altogether.
