### ISSUE TITLE
Drag and drop text inside a Textfield replaced value with "undefined"

### ISSUE THREAD

**Issue by markuso** [tleunen/react-mdl#238]
Some users are used to **moving text around** by dragging and dropping to a new location (within larger textarea fields usually). They select some text and drag it to another position within the same textfield or onto another altogether. This works perfect in native browser input and textarea fields, but not the input or textarea elements that the **Textfield** component renders.

Any ideas on what causes this within the react-mdl library? Anyone else has experienced this behaviour? Content gets wiped fully when this occurs. I am not sure if this is an issue in the upstream MDL library.

Thank you :)

**Comment by tleunen** [comment]
I tried it and everything seem to work. The value is updated after a drag/drop text with the correct value, not undefined.

Do you have an example?

**Comment by markuso** [comment]
My apologies. It seems to be because they are passed props from redux-form. I will investigate further. Thank you and I'll close this issue for now.

**Comment by tleunen** [comment]
Do you update your store with the `onChange` handler?

**Comment by markuso** [comment]
Yes I do.

**Comment by markuso** [comment]
The problem turned out to be within the `onDrop` and `onDragStart` props that `redux-form` passes into the textfield when I wrap the component. I will submit an issue on that repo.

Thanks a lot Tommy :)

**Comment by tleunen** [comment]
np, let me know if I can help ;)
