### ISSUE TITLE
using a web-component (which is implemented with react) inside the Layout component causes an exception

### ISSUE THREAD

**Issue by sangohan** [tleunen/react-mdl#244]
The error message i get is: 
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
```

caused by the div inserted in the layout (with css class 'mdl-layout__inner-container'), which does not have a `data-reactid` attribute.

**Comment by tleunen** [comment]
Can you share en example of code with the error?

**Comment by tleunen** [comment]
Closing this for now... Please provide more information
