### ISSUE TITLE
color styles layout issues

### ISSUE THREAD

**Issue by jdrmar** [tleunen/react-mdl#251]
Hi, I just started using your helpful library today.
It might be that I'm doing something wrong, but it seems like the colored styles (for example material.yellow-red.min.css) behave differently from the material.min.css style.

Notably: 
* the in-focus label:after style for textfield has a background that is not visible on a yellow background (for example when using a textfield in the header behind a search icon)
* the width of the grid when using layout is off (100% in material.min.css, missing in material.yellow-red.min.css)

I'd be happy to help fix this, but I feel this might be an issue that can be handled automatically through the pipeline that generates your /extra files?

**Comment by tleunen** [comment]
Hmm.. It might be an upstream bug in that case, since all the files under `/extra` are generated by the MDL project (https://github.com/google/material-design-lite) with our layout patch.
So it might be on their side, or might be a side effect of the applied layout patch

**Comment by jdrmar** [comment]
Hi Tommy,

Turns out the grid with issue was due to a mistake I made: in an attempt to check why the in-focus color was off, I used the official mdl style, causing the grid to be off. Sorry!

**Comment by tleunen** [comment]
np ;)
