### ISSUE TITLE
Issue when running `npm shrinkwrap`

### ISSUE THREAD

**Issue by unindented** [tleunen/react-mdl#256]
I'm stumped. When running `npm shrinkwrap` on a project that depends on `react-mdl`, I get the following error:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: history@2.0.1 .../node_modules/react-mdl/node_modules/history
```

If I go to `node_modules/react-mdl/node_modules`, I'm indeed seeing `history`:

![screen shot 2016-03-15 at 09 20 42](https://cloud.githubusercontent.com/assets/69485/13773117/9c2b53ce-ea8f-11e5-93d8-52abe85dab52.png)

However, your `package.json` declares `clamp` and `classnames` as the only production dependencies!

WHAT IS GOING ON HERE?

**Comment by jolic** [comment]
Sorry for the post here but

why is "New Issue" disabled?

**Comment by tleunen** [comment]
Is it from a clean install? Which version of node and npm are you using?
It should never install history, as it's not a direct dependency.

@jolic nothing is disabled. If the button is disabled for you, contact github support.

**Comment by jolic** [comment]
"Submit new issue" button is disabled.

**Comment by tleunen** [comment]
You have to specify a title and a description to submit an issue.
If you still have issue, please contact the github support.

Stop posting this here.

**Comment by jolic** [comment]
Unitl waiting for response from Github according the New Issue bug here is a small patch for the drawer:

When the drawer is displayed and the content inside the <Layout/> is greater than the window you can scoll down and the div with ".mdl-layout__obfuscator" is shown but the height is not 100%.
Changing the style of ".mdl-layout__obfuscator" to
```
.mdl-layout__obfuscator{
   ...
   position: fixed;
   ...
}
```
fixes it.

**Comment by unindented** [comment]
@tleunen Fresh install. I've tried `rm -rf node_modules` multiple times, I've tried `npm cache clear`, and I always get the same.

```
$ node --version
v4.4.0
$ npm --version
2.14.20
```

I'm pretty sure npm is at fault here, but if you could verify with a couple of your projects...

**Comment by tleunen** [comment]
I found this https://github.com/npm/npm/issues/9894 and this https://github.com/npm/npm/issues/9642
Looks like, because of the name, it's always pulled.

I never got the issue with npm 3, so if you can, upgrade your npm ;)

**Comment by unindented** [comment]
Ha, nice! Thanks for finding that!
