### ISSUE TITLE
Patch for the Drawer

### ISSUE THREAD

**Issue by jolic** [tleunen/react-mdl#257]
When the drawer is displayed and the content inside the ```<Layout/>``` is greater than the window you can scoll down and the div with ".mdl-layout__obfuscator" is shown but the height is not 100%.
Changing the style of ".mdl-layout__obfuscator" to
```
.mdl-layout__obfuscator{
   ...
   position: fixed;
   ...
}
```
fixes it.

**Comment by tleunen** [comment]
Can this be reproduce with the base MDL? outside of react-mdl?

**Comment by jolic** [comment]
See https://www.getmdl.io/components/index.html#layout-section

When you add some big content inside the ```<main class="mdl-layout__content">...</main>``` on the first example it works as expected.

**Comment by tleunen** [comment]
How do you scroll with the visible obsuscator?
Could you build an example using codepen, jsbin or any other tool like that?

Thanks.

**Comment by jolic** [comment]
As I wrote a codepen I realized that I didn't wrap the content with a ```<Content/>``` component:

http://codepen.io/jolic/pen/wGJvQg

Works as expected.
