### ISSUE TITLE
Add jsnext:main field to package.json

### ISSUE THREAD

**Issue by iamale** [tleunen/react-mdl#259]
This way you can support [rollup.js](http://rollupjs.org) — a relatively new module bundler that (claims to) produce smaller builds than WebPack by using tree-shaking. To support it, you'd add a `jsnext:main` entry to the package.json, like so:

```json
{
  "main": "lib/index.js",
  "jsnext:main": "src/index.js"
}
```

You already include `src/` in your npm releases, and adding one line shouldn't be a problem, I believe.

#### See also
- http://rollup.org
- https://github.com/rollup/rollup/wiki/jsnext:main

**Comment by tleunen** [comment]
Have you tried it? Everything works as expected with rollup?

**Comment by iamale** [comment]
I'm currently trying it out. One problem could be a lot of config to boot up React itself (https://gist.github.com/iamale/fa68da6925b44f567d63), but otherwise it should be OK. I'll write once I manage to start it.

**Comment by iamale** [comment]
Works smoothly so far!
