### ISSUE TITLE
when dragging a Slider with a fixed value, the bubble stays in place but the width of the colored line changes

### ISSUE THREAD

**Issue by vitosamson** [tleunen/react-mdl#261]
sorry if that's a poor title, not really sure how better to explain it. see this screen cap: http://g.recordit.co/jDMmN7oGKd.gif

the component is rendered with `<Slider value={50} max={100} min={0} onChange={e => e.preventDefault()} />`

I suspect this may actually be an issue with mdl itself, but I'm wondering if there's anything that can be done on the react-mdl side to prevent it.

react-mdl@1.5.0
react@0.14.7

**Comment by tleunen** [comment]
Thanks @vitosamson, I'll investigate the issue.

From what I see, because of the custom UI styles, we cannot directly set the value of the input field. We have to use the MDL function to do so (using `MaterialSlider.change(value)`).

**Comment by tleunen** [comment]
Will be fixed in next version.
But, usually the slider must be a controlled component, thus you have to retrieve the value from the `onChange` event and update the value from the slider.
If you want to force a value, without setting the slider as disabled, you could do something like this I guess:
```jsx
<Slider min={0} max={100} value={this.state.value} onChange={e => this.setState({ value: this.state.value })} />
```

**Comment by vitosamson** [comment]
Awesome, thanks for the speedy fix! That's pretty much my use case - it is a controlled component but sometimes I don't want the user to be able to change the value, but also don't want it disabled.

**Comment by tleunen** [comment]
Ok ;)
So yep, you'll still need to "force update" the value, to trigger an update on the component, and thus update the UI for the slider.
Unfortunately, until v2, that's the only way.

**Comment by vitosamson** [comment]
It seems like even with forcing an update via state change the background and button become out of sync. Any eta on v2?

**Comment by tleunen** [comment]
Yep, this is because you still need the fix I did in this commit ;) https://github.com/tleunen/react-mdl/commit/cd1253dc62ae546b14fb6ba47bc74524cd77d7a9

I'll release v1.5.1 later today.. V2 is still experimental and will take a few weeks/months ;)

**Comment by vitosamson** [comment]
Ah gotcha, I thought you'd meant that as a workaround until the commit landed in a release. Will that commit be in 1.5.1?

**Comment by tleunen** [comment]
yep!

**Comment by vitosamson** [comment]
:+1: thanks again for the quick response
