### ISSUE TITLE
window.scrollTo(0,0) doesn't work with Layout component

### ISSUE THREAD

**Issue by marcelpanse** [tleunen/react-mdl#262]
If you use a layout component (with a navigation/drawer) then `window.scrollTo(0,0)` stops working. 
`window.scrollTo(0,0)` is the recommended way for react-router to navigate back to the top when a page changes. 

This problem is also visible at the react-mdl webpage: https://tleunen.github.io/react-mdl/#/lists
Just open the console and type `https://tleunen.github.io/react-mdl/#/lists`.

Because of this bug it is hard for users to navigate around the website (for example if you scroll down and then hit a link, you enter the next page at the bottom).

**Comment by tleunen** [comment]
Unfortunately, it's a limitation of Material Design Lite, because the scrolled content is not the body. It's the content container.

But you can still scroll the container at the top using this
```
document.querySelector('.mdl-layout__content').scrollTop = 0;
```

**Comment by marcelpanse** [comment]
Cool, this seems to work just fine, I will use this workaround. Thanks.
