### ISSUE TITLE
Slider value isRequired, preventing defaultValue

### ISSUE THREAD

**Issue by rektide** [tleunen/react-mdl#263]
Hiya. In Slider, value is required. This is in conflict with the demoes in https://tleunen.github.io/react-mdl/#/sliders , which use defaultValue instead of value: https://tleunen.github.io/react-mdl/#/sliders .

Having both a value and defaultValue gives:  
*Warning: Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components*

**Comment by tleunen** [comment]
The documentation always mentioned them as required, but it wasn't the case in the code. So in the latest version, I set them as required.

The slider is therefore not compatible with the "uncontrolled" way. I should change the demos to reflect that.

**Comment by rektide** [comment]
What kind of work would have to go in to getting uncontrolled supported?

**Comment by tleunen** [comment]
Not much probably...
Just change this line to execute it only when a value is provided.
https://github.com/tleunen/react-mdl/blob/master/src/Slider.js#L16

A PR is welcome to change that.
