### ISSUE TITLE
Layout Header disappeared in small screen

### ISSUE THREAD

**Issue by kkpoon** [tleunen/react-mdl#264]
no matter in Template -> [Article](https://tleunen.github.io/react-mdl/#/templates/article), Template -> [Text](https://tleunen.github.io/react-mdl/#/templates/text)

or

in the example of https://tleunen.github.io/react-mdl/#/navigation-layout

when scale the screen to small width, e.g. 800x600, the layout nav bar disappear no matter `fixedHeader` = true or false

**Comment by sontek** [comment]
Why is this patch required?  I don't see this problem when using MDL directly but do see it when using react-mdl.

**Comment by tleunen** [comment]
The header was not visible in small screen. This patch solved the issue. What's the problem?

**Comment by sontek** [comment]
@tleunen I'm just trying to figure out what is different about `mdl-react` than `mdl` itself.  Here is an example of using MDL directly:

http://codepen.io/sontek/pen/oLZLex

**Comment by tleunen** [comment]
One is using React, the other nothing ;)
Both should look the same
