### ISSUE TITLE
Slider onChange is not called with value but with Event

### ISSUE THREAD

**Issue by greggigon** [tleunen/react-mdl#268]
Hi
First of all, excellent work. 
I think I'm hitting a brick wall with Slider component.
According to docs:

> onChange Function	Callback taking 1 parameter with the new value	Required

However, if I modify the Codepen example to :

`<Slider min={0} max={100} defaultValue={0} onChange={(e) => console.log(e)}/>`

when I move slider, I can see Event, not the Value being passed.
Any ideas?

**Comment by tleunen** [comment]
Thanks for reporting the issue. It's an error in the documentation. You'll receive the event and you can get the value with `e.target.value`.

**Comment by tleunen** [comment]
I'll release the fix in the doc later today when I find some time ;)
