### ISSUE TITLE
Error in MDLComponent.componentDidMount when using JSPM

### ISSUE THREAD

**Issue by alexeyzimarev** [tleunen/react-mdl#271]
I get an error in componentDidMount in MDLComponents.js when using JSPM. I am trying to render a div with one Button inside it:

``` typescript
const App = () => (
    <div>
        <Button raised>Button</Button>
    </div>
);

render(
    <Provider store={store}>
        <App />
    </Provider>
    , document.getElementById("content")
);
```
The button itself gets rendered properly.

If I replace the Button with standard HTML, the error does not appear.

> 22:04:48.903 Error: componentDidMount@http://localhost:8776/jspm_packages/npm/react-mdl@1.5.2/lib/utils/MDLComponent.js:32:13
	.notifyAll@http://localhost:8776/deps.lib.js:8758:13
	ON_DOM_READY_QUEUEING.close@http://localhost:8776/deps.lib.js:5225:7
	Mixin.closeAll@http://localhost:8776/deps.lib.js:8992:15
	Mixin.perform@http://localhost:8776/deps.lib.js:8958:15
	batchedMountComponentIntoNode@http://localhost:8776/deps.lib.js:10718:7
	Mixin.perform@http://localhost:8776/deps.lib.js:8949:17
	ReactDefaultBatchingStrategy.batchedUpdates@http://localhost:8776/deps.lib.js:1454:9
	batchedUpdates@http://localhost:8776/deps.lib.js:9082:7
	ReactMount._renderNewRootComponent@http://localhost:8776/deps.lib.js:10796:9
	ReactMount._renderSubtreeIntoContainer@http://localhost:8776/deps.lib.js:10842:25
	ReactMount.render@http://localhost:8776/deps.lib.js:10849:16
	.execute@http://localhost:8776/src/app.js:51:13

**Comment by tleunen** [comment]
Did you include `material.js`?
My guess is that `componentHandler` is not defined.

**Comment by alexeyzimarev** [comment]
OK, I missed that one.

Now it is different:

> Error: upgradeElementInternal@http://localhost:8776/jspm_packages/npm/react-mdl@1.5.2/extra/material.js:60:1
	componentDidMount@http://localhost:8776/jspm_packages/npm/react-mdl@1.5.2/lib/utils/MDLComponent.js:32:13

**Comment by alexeyzimarev** [comment]
I found that the call to `findDOMNode` returns null, `upgradeElement` gets null for both parameters, although the calling party is a valid React element.

**Comment by alexeyzimarev** [comment]
From what I read, render of stateless components returns null and in such case `findDOMNode` also returns null. I use stateless components.

**Comment by alexeyzimarev** [comment]
Okay, I found it. JSPM has installed both 0.15rc1 and 0.14.7 of React. When I cleaned it up to 0.14.7, everything started work. The question is if react-mdl will keep working on 0.15...

**Comment by tleunen** [comment]
Currently, react-mdl is tested against React 15 rc2 so, yep it will work with 15 ;)
