### ISSUE TITLE
FABButton.propTypes does not contain Button.propTypes

### ISSUE THREAD

**Issue by PavelPZ** [tleunen/react-mdl#273]
It seems that FABButton inherits all props from Button.
Are there any other examples of propTypes inheritance (I mentioned IconButton too)? If yes, I have to modify my TypeScript definition file generator.

**Comment by tleunen** [comment]
Will continue the typescript related questions on https://github.com/tleunen/react-mdl/issues/266

**Comment by PavelPZ** [comment]
Is it really TypeScript question?

E.g. IconButton.js contains
```JavaScript
IconButton.propTypes = {
    className: PropTypes.string,
    name: PropTypes.string.isRequired
};
```

Should not be (from button.js):
```JavaScript
IconButton.propTypes = {
        mini: PropTypes.bool,
        name: PropTypes.string.isRequired,
        accent: PropTypes.bool,
        className: PropTypes.string,
        colored: PropTypes.bool,
        component: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.element,
            PropTypes.func
        ]),
        href: PropTypes.string,
        primary: PropTypes.bool,
        raised: PropTypes.bool,
        ripple: PropTypes.bool
    };
```

**Comment by tleunen** [comment]
Indeed, because `IconButton` is basically a `Button`, it can also accepts all the props from `Button`.

The thing is, I don't think it makes sense to put them in the code. I think `eslint` will warn of unused props if it's the case. So maybe it's something that should only live in the typescript definition?

**Comment by PavelPZ** [comment]
You are right, I will include type inheritance to my generator for those cases:
- FABButton & IconButton inherits from the Button
- what else?
