### ISSUE TITLE
Drawer and title alignment broken

### ISSUE THREAD

**Issue by alexeyzimarev** [tleunen/react-mdl#274]
I took a sample code from the [documentation](https://tleunen.github.io/react-mdl/components/layout/) and the alignment of header elements is broken. Drawer and title row are not aligned vertically, as it is shown in the samples.

![2016-03-28_16-30-51](https://cloud.githubusercontent.com/assets/2821205/14080143/6587a06a-f503-11e5-8f41-6367c61b7669.png)

**Comment by alexeyzimarev** [comment]
I tried to find out what the issue could be but cannot find it, all CSS properties are identical. This is what I see when I run my app:

![2016-03-28_18-06-08](https://cloud.githubusercontent.com/assets/2821205/14082399/034a7492-f510-11e5-81cc-0569019c4ff8.png)

```jsx
const App = () => (
    <Layout>
            <Header title={<span><span style={{ color: '#ddd' }}>Area / </span><strong>The Title</strong></span>}>
                <Navigation>
                    <a href="">Link</a>
                    <a href="">Link</a>
                    <a href="">Link</a>
                    <a href="">Link</a>
                </Navigation>
            </Header>
            <Drawer title="Title">
                <Navigation>
                    <a href="">Link</a>
                    <a href="">Link</a>
                    <a href="">Link</a>
                    <a href="">Link</a>
                </Navigation>
            </Drawer>
            <Content />
    </Layout>
   );

render(
    <App />, document.getElementById("content")
);
```

**index.html**

```html
<html>
<head>
    <title>Examples</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="jspm_packages/npm/react-mdl@1.5.2/extra/material.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="/jspm_packages/system.js"></script>
    <script src="/config.js"></script>
    <!--<script src="/deps.lib.js"></script>-->
    <script>
        System.import("react-mdl/extra/material.js");
        System.import("./src/app");
    </script>
</head>
<body>
    <div id="content"></div>
</body>
</html>
```

**Comment by tleunen** [comment]
Thanks for reporting the issue @alexeyzimarev. I don't see any issue on the website. Can you try to put your code on a codepen and share?

**Comment by alexeyzimarev** [comment]
I found this issue reported on MDL repo long time ago and there was also a workaround provided. I will post it here when I get back home.

**Comment by jdrmar** [comment]
Does adding '<!doctype html>' to the top of your index.html fix it?

**Comment by alexeyzimarev** [comment]
I used this:
```#html
    <style>
        .mdl-layout__drawer-button:before {
            content: '';
        }
    </style>
```

**Comment by alexeyzimarev** [comment]
@jdrmar It actually helped, thank you very much!
