### ISSUE TITLE
Textfield is-invalid added on every change

### ISSUE THREAD

**Issue by mpolichette** [tleunen/react-mdl#277]
Hey guys,

I just started using react-mdl, so i might not be using it correctly, let me know if that is the issue.

I'm attempting to use `react-mdl` with `redux-form` and r and so far it looks like they get along REALLY well.  I'm actually surprised how easy this is.   However, it appears that using the validation tools for `redux-form` causes Textfield to keep adding `is-invalid` on every re-render or basically every time focus or blur the field.

My code:
`<Textfield label="Email" {...email} floatingLabel />`
where `email` is just a redux form field specified by redux forms.

I endup with: 
![screen shot 2016-03-31 at 6 09 50 pm](https://cloud.githubusercontent.com/assets/2925660/14194434/d5543038-f76b-11e5-82f5-6440e954bb51.png)

I hope I've added enough information.  Let me know if I can do more testing.

Thanks for making awesome stuff!
Matt

**Comment by tleunen** [comment]
Thanks for reporting the issue @mpolichette.

Good to know it works well with redux-form :) I'll make sure to fix the issue in the next version.
