### ISSUE TITLE
Badge component does not retain className of a given child

### ISSUE THREAD

**Issue by samoshkin** [tleunen/react-mdl#279]
Currently, `Badge` component works by cloning given child and assigning `mdl-badge` specific classes to it. The issue is that it does not retain existing className, which is set on that child.

Given this code
```
<Badge text={notSeenPendingOrderCount || null}>
    <span className="OrderTabs-tabNewText">NEW</span>
</Badge>
```

`OrderTabs-tabNewText` class name is not present in resulting DOM.

```
<a class="mdl-layout__tab" style="cursor:pointer;" data-reactid=".0.0.1.1.$/=10">
  <span class="mdl-badge" data-reactid=".0.0.1.1.$/=10.0" data-badge="1">New</span>
</a>
```

Should be pretty simple fix:
https://github.com/tleunen/react-mdl/blob/master/src/Badge.js#L31

**Comment by tleunen** [comment]
Thanks @samoshkin. I made a fix to retain the className from the child. At the same time, I also retain the className from the badge component itself, so you'll be able to write this:
```jsx
<Badge text={notSeenPendingOrderCount || null} className="OrderTabs-tabNewText">
    NEW
</Badge>
```
