### ISSUE TITLE
import react-mdl and external links

### ISSUE THREAD

**Issue by xdvarpunen** [tleunen/react-mdl#284]
Are these;
```
<link rel="stylesheet" href="material.css">
<script src="material.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
necessary? Could these be included into npm? 

-XDVarpunen

**Comment by xdvarpunen** [comment]
Actually just read about 2.x update. Font needs to be downloaded externally still though.

**Comment by tleunen** [comment]
You can also import them in your entry point with webpack for example ;)
See https://github.com/tleunen/react-mdl/blob/master/docs/pages/_template.js#L11-L12

**Comment by xdvarpunen** [comment]
Thanks! c:
