### ISSUE TITLE
[v2] Rewrite Tooltip without the need of mdlUpgrade 

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#285]
Currently, the `Tooltip` component requires the javascript code from material design to work properly. We should rewrite the component as a true React component without that dependency.

It should also move in its own directory, with its tests. See `Badge` as an example.

**Comment by darkyen** [comment]
I will take this one.

**Comment by tleunen** [comment]
Thank you @darkyen! :)

**Comment by tleunen** [comment]
Hey @darkyen, any update on this one? ;)
I might jump on it tomorrow, since I'd need it to finish something in the new tests for the Table components.

**Comment by darkyen** [comment]
Oh haven't had enough time because of work. You can hop on it, I will take
other ones :-( sorry!

**Comment by tleunen** [comment]
Np ;-)
