### ISSUE TITLE
[v2] Rewrite Textfield without mdlUpgrade

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#286]
Currently, the `Textfield` component requires the javascript code from material design to work properly. We should rewrite the component as a true React component without that dependency.

It should also move in its own directory, with its tests. See `Badge` as an example.

**Comment by Download** [comment]
Don't forget to render the `props.children` as well when implementing this.

SEE Make Textfield render children #326

**Comment by tleunen** [comment]
Closing this for now while rethinking about v2
