### ISSUE TITLE
Dependency names wrong when using React MDL from script

### ISSUE THREAD

**Issue by Download** [tleunen/react-mdl#298]
I am including React MDL 1.5.3 from [npmcdn](https://npmcdn.com/react-mdl@1.5.3/out/ReactMDL.js).

If you follow that link and inspect the top of the file (UMD header) you see this line;

```js
root["ReactMDL"] = factory(root["react"], root["react-dom"]);
```
...which seems strange. I would expect `React` and `ReactDOM`.
And indeed, I am getting this error:

> ReactMDL.min.js:1026 Uncaught TypeError: Cannot read property 'Component' of undefined

When I inspect the `window` object, prior to React MDL loading, I see that the `React` object is there ,as expected, but not the `react` object that the UMD header is trying to load... again as expected.

Compare with ReactMDL.js at version [1.5.2](https://npmcdn.com/react-mdl@1.5.2/out/ReactMDL.js):

```js
root["ReactMDL"] = factory(root["React"], root["ReactDOM"]);
```

It seems something changed between 1.5.2 and 1.5.3 in Webpack's config that broke this.

**Comment by Download** [comment]
I think it broke in this PR:
https://github.com/tleunen/react-mdl/pull/272/files

**Comment by tleunen** [comment]
Thanks @Download for the investigation.
I'll revert the commit in https://github.com/tleunen/react-mdl/pull/299
