### ISSUE TITLE
data-upgraded causes Warning: React attempted to reuse markup in a container but the checksum was invalid

### ISSUE THREAD

**Issue by Download** [tleunen/react-mdl#302]
I'm using server-side rendering and have been getting warnings about React not re-using the server-side markup because it differs (ever so slightly) from the client generated markup. I'm now trying to get rid of these warning but I'm kinda stuck on this one:

> react.js:19287 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
> (client) n" data-reactid="28">Login</button><nav 
> (server) n" data-reactid="28" data-upgraded=",Mat

I realize that `data-upgraded` is probably added by the material.js script which is actually not part of this project (or shouldn't be at least) and that it will be removed for v2, but I was just wondering if you have experience with this warning and whether you know/think it can be remedied or whether I should just live with it for now?

I have improved my server side and it's now pretty darn fast, but because the server markup can't be reused I get this ugly flash of unstyled content a second or so after the page has loaded.

**Comment by Download** [comment]
My server does not actually render the `data-upgraded` attribute; it is added by material.js after it loads, but before the client has kicked in... Maybe there could be a way to prevent material.js from doing it's work until the client has actually kicked in and rendered for the first time?

**Comment by Download** [comment]
I've done some more digging.

I think I could prevent the issue by changing this code in material.js:

```js
window.addEventListener('load', function() {
  'use strict';

  /**
   * Performs a "Cutting the mustard" test. If the browser supports the features
   * tested, adds a mdl-js class to the <html> element. It then upgrades all MDL
   * components requiring JavaScript.
   */
  if ('classList' in document.createElement('div') &&
      'querySelector' in document &&
      'addEventListener' in window && Array.prototype.forEach) {
    document.documentElement.classList.add('mdl-js');
    componentHandler.upgradeAllRegistered();
  } else {
    /**
     * Dummy function to avoid JS errors.
     */
    componentHandler.upgradeElement = function() {};
    /**
     * Dummy function to avoid JS errors.
     */
    componentHandler.register = function() {};
  }
});
```

My idea is to place this code in a separate function `initializeMDL`, and then let the script check a flag before it assigns this function to `onload`, like this:

```js
if (! window.suppressMDLonLoad) {
  window.addEventListener('load', initializeMDL);
}
```

This would allow me to suppress this behavior initially until after the client has first rendered the markup, at which point I could call `initializeMDL` myself.

What do you think? I realize this will all go away for v2, but it would be helpful (for me at least) until that time to have this.

**Comment by tleunen** [comment]
If you register these events, wouldn't this override the default upgrade and then never upgrade the elements?

**Comment by tleunen** [comment]
Oh nm, I see... So basically, you'll trigger the initialize manually instead of automatically onload, is that right?

**Comment by Download** [comment]
Yeah that was my idea, but it looks like that's not even needed. I think it works because when the React MDL components are mounted they already upgrade themselves. It looks like we could just drop the initial upgrade components in on load altogether and it would work just fine. But I haven't done any serious testing, just clicking around in my app.

**Comment by Download** [comment]
For what it's worth, my app is now live on http://www.bridalapp.net with this change in it. It seems to be working flawlessly so far.

**Comment by tleunen** [comment]
Something is weird, I just remembered that I added this line to make server rendering work https://github.com/tleunen/react-mdl/blob/master/extra/material.js#L4
So in theory, the file should not even be executed.

**Comment by tleunen** [comment]
Merged in master.

**Comment by Download** [comment]
@tleunen 
The problem is that the file executes on the client before React had a chance to render the first view on the client; then when React tries to render, it notices that what it has rendered is different from what the current state of the DOM is.

I think React does a very strict check on the existing state of the DOM when it is rendering for the very first time to decide whether to keep it and start diffing with it straight away, or whether to first discard the old DOM, re-render all the markup to the DOM and use the new DOM as starting point for the diffing process.

Thanks for merging it!

**Comment by tleunen** [comment]
Yeah sorry, for some reasons I thought the issue was on server, but after reading it it was clear it was the client ;)
