### ISSUE TITLE
Without an onchange handler a textfield throws errors

### ISSUE THREAD

**Issue by janpieterz** [tleunen/react-mdl#31]
Because of https://github.com/tleunen/react-mdl/blob/master/src/Textfield.js#L39 when there is no onchange handler connected to a textfield, it throws an error.

**Comment by tleunen** [comment]
`onChange` is actually needed, otherwise you can't get the updated value

**Comment by janpieterz** [comment]
That depends on your setup. For example, using the this.refs you can access the value as well, depending on your setup. This way you don't have to handle every single input's change manually if this is not needed.

https://facebook.github.io/react/docs/more-about-refs.html
https://facebook.github.io/react/docs/working-with-the-browser.html

**Comment by tleunen** [comment]
The input is currently a controlled input, so the value displayed is always the value specified. That's why there's a onChange event.
If we want to modify that, we would need to make the onChange callback optional and modify the value for `defaultValue`. But I usually prefer playing with controlled component. I'm open to discussions though.

**Comment by janpieterz** [comment]
Yeah, I have currently changed them to be controlled inputs, using your handy helper to set the state easily. I don't mind either way, I think since React itself allows it it should be allowed as well, but that's just my 10 cents ;)

**Comment by tleunen** [comment]
Yep but because we use the `value` property on the input, if we don't use the `onChange` callback, React will warn about this ;)

**Comment by janpieterz** [comment]
Maybe this is just me (relatively new to React), but couldn't we just set the value on the input conditionally, and therefore also the make onChange callback conditional?
