### ISSUE TITLE
Unable to use ref with Components created with utils.basicClassCreator

### ISSUE THREAD

**Issue by dimik** [tleunen/react-mdl#312]
I got this warning with the latest React and ref has a null value

> Warning: Stateless function components cannot be given refs (See ref "myList" in List created by MyComponent). Attempts to access this ref will fail.

i believe it's because of your basicClassCreator returns arrow function instead of real Component Class
You can check the React documentation about it
https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

> NOTE:
> Because stateless functions don't have a backing instance, you can't attach a ref to a stateless function component.

**Comment by tleunen** [comment]
Yes, because they are SFC.

What's your usecase?

**Comment by dimik** [comment]
I have List with overflow: scroll and need to set scrollTop=0 on it in event handler

**Comment by tleunen** [comment]
Better to wrap your component in a class component to be able to use the ref if this is your need.
