### ISSUE TITLE
Cell and Grid shadow option doesn't work ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [tleunen/react-mdl#314]
Hi, ss I said on the topic, anyone met the same prob as mine ? 

Thx a lot.

**Comment by tleunen** [comment]
Looks like `shadow={3}` doesn't work, but the others seem to be fine.

You can see in this file we only accept a number from 0 to 6 (included): https://github.com/tleunen/react-mdl/blob/master/src/utils/shadows.js

Also, currently the prop value doesn't match the real shadow value, this should be improved (and add the missing values (see https://github.com/google/material-design-lite/blob/master/src/shadow/_shadow.scss)
