### ISSUE TITLE
How to handle events in DataTable?

### ISSUE THREAD

**Issue by Natanael1234** [tleunen/react-mdl#319]
How to handle events like clicks in a specific row or column?

**Comment by tleunen** [comment]
Clicking an entire row or column is unfortunately not possible, but you should be able to put a button or any other component in a cell with a custom renderer (with `cellFormatter`).

**Comment by Natanael1234** [comment]
I already solved this problem. You can pass an react component with an onclick event inside the array passed as rows parameter.
