### ISSUE TITLE
import ReactMDL from 'react-mdl'; not working

### ISSUE THREAD

**Issue by achtan** [tleunen/react-mdl#320]
````
import ReactMDL from 'react-mdl';

console.log(ReactMDL); // undefined
`````
version `1.5.4`

**Comment by tleunen** [comment]
Are you sure? I checked the build on npm and everything looks ok.

**Comment by saravanan4514** [comment]
I'm getting the same issue as well. export reactMDL is missing in the index.js file. Kindly let me know if i have missed anything.

**Comment by tleunen** [comment]
Oh I think you're right. Only the specific components seem exported here https://github.com/tleunen/react-mdl/blob/master/src/index.js

**Comment by saravanan4514** [comment]
Loading specific components we get an error "Cannot read property 'upgradeElement' of undefined". I tried using Button and checkbox component.

**Comment by tleunen** [comment]
Do you lead the material.js file before using React-MDL?
This is required to get the `upgradeElement`. Read: https://github.com/tleunen/react-mdl#requirements

I know this is not ideal and will be resolved in the next major version.

**Comment by saravanan4514** [comment]
Thank you so much for your valuable response. Awaiting for the next major version.

**Comment by tleunen** [comment]
Btw, to resolve the undefined issue when using this `import ReactMDL from 'react-mdl';`

You can use this instead:
```js
import * as ReactMDL from 'react-mdl';
```

But I highly suggest you to grab the specific components you want by using the direct path to the component `react-mdl/lib/Button` or using this syntax: `import { Button }  from 'react-mdl`.
