### ISSUE TITLE
Maybe use a ul for radiogroup ?

### ISSUE THREAD

**Issue by darkyen** [tleunen/react-mdl#33]
Right now it uses a bunch of labels, just saying shouldn't it be ul ? seperate li's make it much simpler to style.

**Comment by tleunen** [comment]
The label is there so you can click on the whole thing and check the input.

But I think we could easily do that if the radio button are inside a radio group.

**Comment by darkyen** [comment]
\o/

**Comment by tleunen** [comment]
Hmm.. Instead of forcing the use of `ul` and `li`. I'll add 2 more props to the component to set the root container and the container for each radio button. What do you think?
This way, we can keep use whatever we want... ul and li, dl and dt/dd or just div.
