### ISSUE TITLE
FABButton nor any other Buttons work

### ISSUE THREAD

**Issue by jasan-s** [tleunen/react-mdl#331]
i did the following:

```
import 'react-mdl/extra/material'
import 'react-mdl/extra/material.css'
import { FABButton, Icon } from 'react-mdl'
```

and then 

```
    <FABButton
      colored = {true}
      raised = {true} >
      <Icon name={'hello'} />
    </FABButton>
```

I get the following result:
![fabbutton](https://cloud.githubusercontent.com/assets/13863953/16295460/e5dd03f6-38db-11e6-901c-bb118e1264ee.jpg)

I was expecting this:
![fabbutton](https://cloud.githubusercontent.com/assets/13863953/16295487/0edc3a6a-38dc-11e6-888a-022dd0a2ae86.jpg)

**Comment by tleunen** [comment]
Hmm.. Just tried on codepen and everything seems ok: http://codepen.io/anon/pen/VjmNad?editors=001

Make sure the styles are loaded properly in your setup

**Comment by jasan-s** [comment]
@tleunen  it seems to work with cdn link so is this import statement incorrect? 

```import 'react-mdl/extra/material'
import 'react-mdl/extra/material.css'```

**Comment by jasan-s** [comment]
also is it possible to change color of this button?

**Comment by tleunen** [comment]
Your imports look ok. Maybe the issue is inside your css loader?

**Comment by tleunen** [comment]
Is this working for you now @jasan-s ?
