### ISSUE TITLE
ListItem : Add more props

### ISSUE THREAD

**Issue by khacthanh** [tleunen/react-mdl#334]
ListItem is usualy component to use, it's great if has some props:
+ Image (round or rect) replace icon
+ Click/Touch event callback

**Comment by tleunen** [comment]
We could make `icon` to be a string, or a component.
That way you can use an image, and put events on it.

Any help is welcome.

**Comment by rushabhy** [comment]
Can I give it a try?

**Comment by tleunen** [comment]
I just checked, and `<ListItemContent>` already allow for a `string` or an `element`. So you can build an image before sending it to the component.

Closing it.
