### ISSUE TITLE
[Textfield] Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by 1j01** [tleunen/react-mdl#335]
Using `Textfield` with the latest version of React (v15.1.0) gives me this error:

Uncaught Invariant Violation: `addComponentAsRefTo(...)`: Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)

**Comment by 1j01** [comment]
So react-mdl.js includes a bundled version of React? Would https://github.com/tleunen/react-mdl/issues/286 fix this?

**Comment by tleunen** [comment]
The bundle file does not include React.

For the ref, the Textfield component set a ref on an `input` or a `textarea`, but that's the only ref, which is valid.

Can you share some code to replicate the error?

**Comment by 1j01** [comment]
Oh, ah, I see, the bundle *I made* includes react. I couldn't find out how to include the module in a browser so I used browserify to export `ReactMDL` to a global. Is there an official bundle somewhere?

**Comment by 1j01** [comment]
Okay, I found the bundle viewing the source on the examples. It would be good to improve the documentation though as I had no idea how to get started. Why isn't the bundle in `extras/`?

**Comment by 1j01** [comment]
Do I have to use browserify? It's on my TODO to use it in my app, but I don't want to lose my auto-reloading workflow and watchify isn't working. (I've tried multiple operating systems.)

**Comment by Download** [comment]
@1j01 I recognize what you are struggling with. The whole bundling process takes some time to get used to. Personally I would recommend trying [Webpack](https://webpack.github.io/) with [Babel](https://babeljs.io/) and the [React preset](https://babeljs.io/docs/plugins/preset-react/). It seems to be what most devs are using.

A good starting point might be one of the many [starter kits](https://www.google.com#q=react%20starter%20kit) out there. Once you get that working correctly, adding React MDL is pretty simple actually. But now you are doing both at the same time and it can become very confusing quickly.

**Comment by Download** [comment]
[quote]Oh, ah, I see, the bundle I made includes react. I couldn't find out how to include the module in a browser so I used browserify to export ReactMDL to a global. Is there an official bundle somewhere?[/quote]

From your comments I am assuming you at one point did

```sh
npm install --save react
```

You are installing a Node module in that case. You can use Browserify or Webpack to package that for the web into your own library (as you are currently doing), but you can also configure either tool to not bundle React into your own bundle. In the case of Webpack you do this using by marking React as `external` in your config. Something like this:

```js
module.exports = {
	externals: {
		'react': 'React',
		'react-dom': 'ReactDOM',
		'react-mdl': 'ReactMDL',
	}
};
```

What this config does is tell Webpack: I am using modules `react`, `react-dom` and `react-mdl` from external scripts, load them from the global objects `React`, `ReactDOM` and `ReactMDL` respectively. They will then be excluded from your own bundle and you can load them from e.g. CDN using an old-fashioned script tag on the web.

**Comment by 1j01** [comment]
Alright, thanks for your help!
