### ISSUE TITLE
Where to find documentation on using the components for more then visual?

### ISSUE THREAD

**Issue by sontek** [tleunen/react-mdl#340]
Hey, I'm starting to use react-mdl for the first time and visually I have everything working perfectly but now I need to start adding functionality and having a hard time finding docs on it.  For example here is a Login component:

```jsx

const SignIn = () => {
    let email = '';
    let password = '';

    return (
        <mdl.Grid>
            <mdl.Spacer />
            <mdl.Cell col={4}>
                <mdl.Card style={{width: '100%'}}>
                    <mdl.CardText>
                        <form action="#">
                            <mdl.Textfield
                                onChange={(val) => { email = val.target.value; }}
                                label="E-mail"
                                floatingLabel
                                required
                            />
                            <mdl.Textfield
                                onChange={(val) => { password = val.target.value; }}
                                type="password"
                                label="Password"
                                floatingLabel
                                required
                            />
                            <mdl.Checkbox label="Remember Me"/>
                        </form>
                    </mdl.CardText>
                    <mdl.CardActions>
                        <mdl.Button colored>Forgot Password</mdl.Button>
                        <mdl.Button colored raised ripple onClick={() => {console.log("Logging in"); } }>Sign In</mdl.Button>
                    </mdl.CardActions>
                </mdl.Card>
            </mdl.Cell>
            <mdl.Spacer />
        </mdl.Grid>
    );
};
```

I'd like to do a few things:

- Don't submit the login attempt if the validation on either textbox fails
- Don't highlight the textboxes as invalid when the page renders, only if they try to submit and haven't filled it out yet
- If the try to submit and the textboxes are valid, change the text of the Sign in button and disable it so they can't attempt multiple times.

**Comment by tleunen** [comment]
Hey @sontek, 
- You can add logic (inside the component or outside, depending on your app) to check the data before submitting it.
- I believe it's because of the default rendering of the required textfield (I remember seeing a ticket for that in MDL). One way could be to not set it as required and manage the error youself (with the `error` prop).
- Same thing, you can do that by managing a state (inside your component or outside)
