### ISSUE TITLE
Using Navigation Header Layout

### ISSUE THREAD

**Issue by woniesong92** [tleunen/react-mdl#345]
```html
      <div className="user-navigation-header">
        <Layout>
          <Header>
            <Navigation>
              <Link to="/">Root</Link>
              <Link to="/users/interviews">Interviews</Link>
              <Link to="/users/calendar">Calendar</Link>
              <Link to="/users/profile/1">My profile</Link>
              <Link to="/#">Sign out</Link>
            </Navigation>
          </Header>
          <Drawer>
            <Navigation>
              <Link to="/">Root</Link>
              <Link to="/users/interviews">Interviews</Link>
              <Link to="/users/calendar">Calendar</Link>
              <Link to="/users/profile/1">My profile</Link>
              <Link to="/#">Sign out</Link>
            </Navigation>
          </Drawer>
        </Layout>
      </div>
```

Assume this is my header navigation. I noticed that the layout is set to have `absolute` and `height: 100%`, effectively overshadowing all the main content. I cannot click the main content unless I manually set the `mdl-layout mdl-js-layout has-drawer is-upgraded` class to not have `position: absolute` attribute.

Do you have a solution to this?

**Comment by tleunen** [comment]
What are you trying to achieve?
The `Layout` component should be the "root" (or really close to the root) of your app. The "main content" is a child of the layout.
You can see examples here: http://tleunen.github.io/react-mdl/components/layout/

**Comment by woniesong92** [comment]
I see, thanks. I wanted the `HeaderNavigation` component to be individual from the other components, so I can plug in and out as I want. I figured that the hamburger menu and the drawer only work if I enclose both `Drawer` and `Header` inside a `Layout` component, so that's what I did.

**Comment by tleunen** [comment]
Yep currently, there's no other way. You can still make them in a separate component and decide to show/hide the header if needed though.
