### ISSUE TITLE
[DataTable] onSelectionChanged return rows, what about row object id?

### ISSUE THREAD

**Issue by xdvarpunen** [tleunen/react-mdl#346]
Hi,

DataTable onSelectionChanged returns row number. In order to create database queries one wants to get id of the object in the row, not the row id. Is there way to get row object id in DataTable/access DataTable row object?

-XDVarpunen

**Comment by xdvarpunen** [comment]
Found it; rowKeyColumn attribute sets row id equivalent to assigned object id

**Comment by tleunen** [comment]
The value inside the array can be 3 things, in this order:
- The value of `rowKeyColumn` from the row,
- The value of `key`
- The index value

So if you set a `rowKeyColumn`, which is suggested, it will use that :)
