### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by 1j01** [tleunen/react-mdl#352]
When I was getting started with this project I had no idea how to include and access the library.
I ended up creating my own browser bundle with browserify, which worked for a while until I [ran into a problem](https://github.com/tleunen/react-mdl/issues/335) because my bundle contained a second copy of React.
I only found out from [this closed issue](https://github.com/tleunen/react-mdl/issues/239) that there is already a browser bundle, `ReactMDL.js`. It's just only on `npm` and not in the repo, even though there's [lots of other stuff](https://github.com/tleunen/react-mdl/tree/master/extra) in the repo for distribution purposes.
(I've since [updated my usage](https://github.com/1j01/natter/commit/5dd2828ce25705fcd3ab7f6cedeb6ff183564979), getting rid of webpack.)

The README should explain how to install and include the library.
You don't need to `import` it (which isn't supported in major browsers), or use browserify or webpack, you can just copy `node_modules/react-mdl/out/ReactMDL.js` to a `lib` or `vendor` folder and include it as a script (unless you have a setup where you can rely on the existence of `node_modules`)

I could create a PR with some improvements.

**Comment by tleunen** [comment]
Hi @1j01, 

I understand the way you do to use the library will also work, but most users will use webpack or browserify to bundle their project, and therefore include react-mdl using the same way.

Either way, I also believe a "getting started" document might help people to better understand how to use the lib. Would you want to help on this?

**Comment by 1j01** [comment]
Yes, it should explain how to use it with webpack or browserify. I'd be using one of those if I could get a live-reloading working with either.
So, were you thinking this should be a separate document? I was thinking of just having all the information on the README, except for the external examples (which benefit from the interactivity). In other words, READMEs are generally the getting started documents, no?

**Comment by tleunen** [comment]
Having it in the readme is fine, unless it becomes too big. Either way, we can start with that and move it in another file later if necessary.

**Comment by 1j01** [comment]
Sounds good, I'll send a PR soon.
