### ISSUE TITLE
Extra layout patch removes drawer button existence check

### ISSUE THREAD

**Issue by dimik** [tleunen/react-mdl#354]
In our app drawer button shouldn't be created with componentHandler, but it creates extra copy now

Please remove [this](https://github.com/tleunen/react-mdl/blob/master/extra/layout-patch.diff#L196-L219) from your patch and rebuild extra files

**Comment by tleunen** [comment]
Hi @dimik,

Thanks for reporting the issue. Is it happening because you're creating the drawer manually?
