### ISSUE TITLE
Fixed error if there are no children in the header

### ISSUE THREAD

**Issue by Graf009** [tleunen/react-mdl#36]
Here is an example that reproduces the error https://gist.github.com/Graf009/ddef4109d157046ac62a
Solution: https://github.com/tleunen/react-mdl/pull/22

**Comment by Graf009** [comment]
https://github.com/tleunen/react-mdl/pull/22

**Comment by tleunen** [comment]
Damn, I didn't test the right thing :D Ok I keep this one open and will retest this later :)

**Comment by tleunen** [comment]
Fixed with #22 :) Thanks @Graf009 and sorry about that, should have been merged a while ago
