### ISSUE TITLE
Shrink size of react-mdl

### ISSUE THREAD

**Issue by leipert** [tleunen/react-mdl#367]
Hey there,

First of all: Thanks for your work 👍 

I just peeked into my node_modules folder and i found, that react-mdl takes up about ~45MB of disk space which is around 10% of my total node_modules folder. ([the reason i looked](https://medium.com/friendship-dot-js/b89f63d21558))

Is it really necessary to have ALL css files in `/extra` installed by react-mdl or could `/extra/css` be put into the `.npmignore`?

**Comment by tleunen** [comment]
Users could use custom css for custom styles so yes unfortunately this is required :/

With v2, this process will be a lot easier and users will be able to customize the styles using settings file instead.

Be patient ^^ ;)
