### ISSUE TITLE
Dialog position is off the screen

### ISSUE THREAD

**Issue by pablocubico** [tleunen/react-mdl#370]
I can't see the Dialog opened by using the component, I think the offending line is:

https://github.com/tleunen/react-mdl/blob/master/src/Dialog/Dialog.js#L30

Which takes `body.clientHeight` into account. 

For a dialog over a fixed overlay, I would use the window height instead of the body, to ensure that the dialog is placed within the limits of the viewport.

The Dialog is getting these styles:
<img width="258" alt="captura de pantalla 2016-08-16 a las 15 51 03" src="https://cloud.githubusercontent.com/assets/340766/17711785/901496a0-63c9-11e6-9d32-b6c3dcc98651.png">

Which are obviously based on the calculations made using `body.clientHeight`:
<img width="194" alt="captura de pantalla 2016-08-16 a las 15 51 29" src="https://cloud.githubusercontent.com/assets/340766/17711796/9fee73a2-63c9-11e6-9c57-3f962b3e4c2d.png">

I can make a pull request to fix that line if you need me to.

**Comment by tleunen** [comment]
Hmm indeed, it seems the `window.innerHeight` is more appropriate.
Thanks for the report! And yes, a PR is always welcome :)
