### ISSUE TITLE
[1.7.0] Clicking on a tab adds #react-mdl-tabs-hack into URL

### ISSUE THREAD

**Issue by HriBB** [tleunen/react-mdl#381]
It is [this](https://github.com/tleunen/react-mdl/commit/ca9309e010e26dc612608aa39e6613f8e5560ec9#diff-3f7be4fdbeb919e491cc2c025de5541bL40) code that does it. Had to revert back to `v1.6.1` which works as expected with `HeaderTabs`.

We should find a better solution, or fix it on the `mdl` side. Appending `#react-mdl-tabs-hack` to the URL is not an option for me.

**Comment by tleunen** [comment]
Yay :/
I believe I'll make a monkey patch on the MDL side to remove the `href` check to show the panels. It doesn't make sense in a react world.

Trying to fix it since the beginning with the href but it definitely doesn't work.

**Comment by HriBB** [comment]
Yeah `mdl@v1` is not very react-friendly. I believe that monkey patch is the only solution for this problem ATM, because I think they wont accept any PRs on the `mdl` for this. Anyway, let me know how I can help. I can even write the patch if you just point me into the right direction.

**Comment by tleunen** [comment]
The way I currently patch MDL is by fetching their 1.2.0 version, applying my current patch on it, and then modify the things I have to update. Generating the new MDL version with the changes (with `gulp all` on the MDL repo). Then creating the patch from the changed files/commits.

I'll do this tonight after work, but if you want to do it, go ahead ;)

**Comment by HriBB** [comment]
Uhh I think I'll leave this one to you :) It would probably take me way too long to get everything right. But I will test as soon as you patch it ;)

I want to focus on missing form components which I require for my app: `react-mdl-autocomplete`, `react-mdl-datetime` and fix `react-mdl-selectfield` to use chips at least.

I really hope they release `v2 alpha` soon, it's kinda frustrating having to work with `v1`.

**Comment by HriBB** [comment]
@tleunen when do you plan to release this? I would like to test it + `HeaderTabs` ripple effect.

**Comment by tleunen** [comment]
Sorry @HriBB, I'll probably do it later today.

**Comment by HriBB** [comment]
@tleunen no worries, did not mean to rush you or anything, I was just wondering when it's gonna be released. Take your time, I know that you've got more important stuff to do :)
