### ISSUE TITLE
[Chip] Having more than one child doubles the first one(?)

### ISSUE THREAD

**Issue by igorsantos07** [tleunen/react-mdl#384]
[Codepen](http://codepen.io/anon/pen/yJdBOO?&editors=001)

```js
render() {
  let computedValue = 10
  return <Chip>Cool chip {computedValue}</Chip>
}
```
renders something like `(Cool chip Cool chip 10)`

There's also a warning on the console about `flattenChildren()` finding two children with the same key `.0`. I could workaround this by using `<Chip><span>Cool chip {computedValue}</span></Chip>` but that sounds hackish / verbose :)

**Comment by tleunen** [comment]
Thanks for reporting this @igorsantos07
