### ISSUE TITLE
[help][suggestions] Transitions ?

### ISSUE THREAD

**Issue by darkyen** [tleunen/react-mdl#39]
mdl is a micro-library which specifically states that it is not a framework and hence it does not deal with the framework savvy stuff. But `react-mdl` differs to that as it is a binding of mdl into react. 

As per md spec, meaningful transitions are extremely important to material design and though for mdl it is out-of-scope to dicuss that, I think we should either have some helpers or atleast a discussion on various animation techniques that can be used for material transitions in react.

**Comment by tleunen** [comment]
Could you explain or give an example?

**Comment by darkyen** [comment]
How about we discuss about it on gitter ? then comment the gist of it her ?

**Comment by darkyen** [comment]
@tleunen  ?

**Comment by tleunen** [comment]
Sorry I'm quite busy at work these past few days and when back home, I'm not always on the computer either ;) Depending on the timezone, it could be hard to be connected at the same time though.

Do you mind explaining it here, and if it gets complicated, we'll try finding some time to chat about it

**Comment by darkyen** [comment]
Sure. I think we can make a simple component(s) like which facilate animation squences for material design, or we can simply just make a microlib that does it and make a seperate repo. 

https://github.com/lgvalle/Material-Animations 

The above animation look pretty declarative to me and with react-animate this should be relatively easy to implement.

**Comment by tleunen** [comment]
Yeah, I think it's better to put that in another repo, and maybe use it inside this one (or keep it separated and let users do the integration).

**Comment by darkyen** [comment]
Makes sense.
