### ISSUE TITLE
componentWillUnmount not called

### ISSUE THREAD

**Issue by tleunen** [tleunen/react-mdl#4]
`componentWillUnmount` is never called if the application uses the Layout component.

The Layout component in MDL modify the tree because it creates a container and move the initial node inside the newly created container, which seems to cause some issues for React.
The result of this is that `componentWillUnmount` for the components inside Layout (which means all the components)

Not a lot of solutions here... Either we re-create the component ourselves, or we can find a good way to fix the initial MDL component. I'm for the later, and I'll try to find a good way to fix it.

cc @darkyen

**Comment by tleunen** [comment]
I submitted a fix in the MDL repo but unfortunately it won't land before v2...

**Comment by darkyen** [comment]
An approach taken by react-winjs uses hooks to inject components inside on function callbacks, i guess we can't do much here because react doesn't like changes occuring outside its virtual dom.
