### ISSUE TITLE
Custom component for buttons

### ISSUE THREAD

**Issue by faergeek** [tleunen/react-mdl#40]
It would be great to allow passing needed component as a prop to use something other than `button`.

For example I'd like to have a link that looks like a button and would be cool if `react-mdl` could handle that.
See https://facebook.github.io/react/docs/animation.html#rendering-a-different-component

Also would be cool if it could "guess" what I'm trying to do based on passed props, i.e. if I pass `href` then I want it to render `a` tag.
See http://react-bootstrap.github.io/components.html#buttons-tags

Some examples:
```javascript
<Button>button</Button>
<Button component="a">anchor tag</Button>
<Button href="#">anchor tag</Button>
<Button component={Link}>Link component from react-router</Button>
```

If you like the idea, but you're busy I could submit pull request.

**Comment by tleunen** [comment]
I really like the idea. And yes you can submit a PR for that. I'm still quite busy these days :/
Thanks!

**Comment by faergeek** [comment]
I think actually it may be needed in many other places. May be we should write some mixin-link solution for that.
