### ISSUE TITLE
Is there a way to implement DataTable click through?

### ISSUE THREAD

**Issue by yaoxiao4** [tleunen/react-mdl#401]
Hi, I've been using DataTable and I want to link each row to a different page (link is an attribute in each itme), was wondering if that's possible and how would I go about doing it

**Comment by tleunen** [comment]
There's currently no way to click on an entire row. You would have to add a button or something in a column to achieve this

**Comment by yaoxiao4** [comment]
what about an individual cell

**Comment by tleunen** [comment]
If you set a custom cell formatter to display a link that takes the entire space, I believe it should work ;)

**Comment by yaoxiao4** [comment]
that worked! thanks
