### ISSUE TITLE
Header Title clickable?

### ISSUE THREAD

**Issue by wrick17** [tleunen/react-mdl#403]
Can we add a property to both Header and Drawer which we can use to handle the click on the title of the drawer or header?

**Comment by tleunen** [comment]
The `title` in `Header` can receive an element instead of a string, so you can pass a link.
```jsx
<Header title={<a href="/go">Title</a>}>{...}</Header>
```

The drawer also supports this.

**Comment by wrick17** [comment]
Thanks.
