### ISSUE TITLE
Make onChange optional on TextFields

### ISSUE THREAD

**Issue by Pagebakers** [tleunen/react-mdl#41]
Right now you are forced to use onChange on all fields.

I would prefer to use valueLink instead and making onChange optional.

`valueLink={this.linkState('name')}`

Any plans to support this?

**Comment by tleunen** [comment]
What's `valueLink`? Can't you do the same with `onChange`?
```
onChange={this.linkState('name')}
```
I'm using this on a project and it's working fine.

**Comment by Pagebakers** [comment]
It's part of the LinkedStateMixin 

see https://facebook.github.io/react/docs/two-way-binding-helpers.html

Attaching this to onChange doesn't work unfortunately.

**Comment by tleunen** [comment]
Ok I see, you should already be able to use this.
Any "unknown" props received on the Textfield are passed to the `input` or `textarea` so the valueLink should be properly set as well.

But yes, for now you have to provide an onchange (in this case it can be an empty function). And I agree to set the callback optional.

**Comment by Pagebakers** [comment]
Yes good job on the unknown props, that works great.

Although when using valueLink, an onChange handler is not allowed. For now I'll use your way of binding the state.
