### ISSUE TITLE
Problem with material icons

### ISSUE THREAD

**Issue by artsx** [tleunen/react-mdl#410]
Hello,
Only on chrome I've a problem with material icons.
When i choose icon the render is only text 
<img width="223" alt="screen shot 2016-09-29 at 16 46 09" src="https://cloud.githubusercontent.com/assets/7711803/18958933/a9050574-8664-11e6-823c-fb1d53ab60d5.png">

And on my console log : 
```OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
localhost/:1 Failed to decode downloaded font: https://fonts.gstatic.com/s/materialicons/v18/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2```

Any suggestion ?

Best regards,

**Comment by tleunen** [comment]
Maybe a temporary error with Chrome? If you still have it, try to fill an issue on Chrome, but unfortunately it doesn't see related to react-mdl.
