### ISSUE TITLE
Textfields missing 'is-invalid' when error is set.

### ISSUE THREAD

**Issue by Pagebakers** [tleunen/react-mdl#42]
Errors are never shown because the `is-invalid` className is not added when an error is set.

**Comment by tleunen** [comment]
For now, the `is-invalid` state is only set when the value doesn't match the provided `pattern`. There's some discussions about the textfield here https://github.com/tleunen/react-mdl/issues/37
We're trying to find the best available solution to resolve this.

**Comment by tleunen** [comment]
Fixed by merging #49

**Comment by kctang** [comment]
These fields:

```javascript
<Textfield name="check1" label="Email" error="something wrong" pattern="" defaultValue="bla"/>
<Textfield name="check2" label="Email" error="this error message not showing" defaultValue="bla"/>
```

Current behavior on component render:
* check1 shows error.
* check2 does not show error

Would be better if `check2` also show error because pattern is not set.

**Comment by tleunen** [comment]
I thought we were handling the case but I guess not. Could you please open a new ticket to track the issue?

**Comment by jolic** [comment]
Wouldn't it be good to add a callback when an input item isn't valid?

Something like:
```
<Textfield
                onChange = {() => {}}
                pattern='....'
                error="Show this error"
                label="Test"
                isValid = {(isValid) => { console.log("This item is: "+valid); } }
            />
```

Currently only the parent element of the input gets the classname "is-invalid".

**Comment by tleunen** [comment]
I think you can use the `onInvalid` event, or the `onChange` event and check the validity of the input field there.
