### ISSUE TITLE
What's the preferred quote style?

### ISSUE THREAD

**Issue by faergeek** [tleunen/react-mdl#44]
From [`eslint-plugin-react` docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-quotes.md)
>It takes an option as the second parameter which can be "double" or "single" for double-quotes or single-quotes respectively. **There is no default**.

So what's the preferred style?
I'm asking because that rule is deprecated and should be replaced by [native eslint option](http://eslint.org/docs/rules/jsx-quotes).

**Comment by tleunen** [comment]
I usually use single quotes in JS but double quotes in html (and therefore JSX). Probably need to update the `.eslintrc` file to reflect the change

**Comment by faergeek** [comment]
No, it's not `double`, try to set `double` explicitly and lint sources.

**Comment by faergeek** [comment]
I can submit PR for that too :-)

**Comment by tleunen** [comment]
It's actually `prefer-double` ;)

**Comment by faergeek** [comment]
In native, yes.

**Comment by tleunen** [comment]
Do you mean we don't inherit from it because it's not part of the recommended eslint configuration?

**Comment by faergeek** [comment]
I mean that in `eslint-plugin-react` there was no default value for that option, so I assume that rule didn't ever work.
But for native eslint option there's default value `prefer-double`.

**Comment by tleunen** [comment]
Indeed we never used the rule from `eslint-plugin-react`. I didn't know it existed. Probably it has been added after I integrated it.
About the recommended eslint, we're using it then.
