### ISSUE TITLE
Some components may not upgrade on remount

### ISSUE THREAD

**Issue by faergeek** [tleunen/react-mdl#47]
I noticed that some components (in my case tooltips) do not work after remount.

After some investigation I noticed that mdl expects root node of component as an argument, but tooltip returns wrapper around that node.

So I think we should try to upgrade/downgrade DOM node found using something like this:

```javascript
React.findDOMNode(this.refs.mdlComponent || this)
```

**Comment by Graf009** [comment]
I think that it is necessary for all the components through the use of links refs

**Comment by faergeek** [comment]
It's really needed just for Tooltip, for others `React.findDOMNode(this)` is enough for now.

**Comment by Graf009** [comment]
I use the react-modal, and I have problems with the same problems React.findDOMNode (this).

**Comment by tleunen** [comment]
fixed by #48
