### ISSUE TITLE
onClick on a Button?

### ISSUE THREAD

**Issue by marcelpanse** [tleunen/react-mdl#5]
How do I add an onClick function to a MDL Button? 

```jsx
<Button primary={true} raised={true} ripple={true} onClick={this.doSomething}>Login</Button>
```

doSomething never gets called. It does work with onChange on a Checkbox. I checked the sources and it seems that the checkbox adds the onChange to the props, but button does not. Is that it, or should it work out of the box?

**Comment by bvleur** [comment]
The `onClick` event for Button is working fine for me (react-mdl@0.9.1)

**Comment by marcelpanse** [comment]
Typo on my side, apologies!
