### ISSUE TITLE
Can you please publish latest changes on npm?

### ISSUE THREAD

**Issue by faergeek** [tleunen/react-mdl#52]

**Comment by tleunen** [comment]
Done. `0.13`

**Comment by vmakhaev** [comment]
I open this question again, cause last changes were published almost month ago.
Also FYI, you can make separate commits for version change and add git tags with `npm version` command.

**Comment by tleunen** [comment]
I know It's been a long time :/
So many changes since last version, I still have a few things I want to finish first.
A new version should land in the next couple of days, alongside with the support of MDL 1.0.6 for the Layout component

**Comment by vmakhaev** [comment]
Looking forward to have it.

BTW, as I understand 1.0.6 is last version for 1.0 and then mdl will start 1.1 version. I suppose they have some reasons for this, like breaking changes or something. Do this solve react-mdl issue with Layout? Or it will be only in mdl 2.0?

**Comment by tleunen** [comment]
You're right by saying 1.0.6 "should" be the last version of 1.0.
1.1 will contains a few new components.
But because the layout has to be redesigned, it's a breaking change and this can land only on 2.x :/

**Comment by vmakhaev** [comment]
Ok, at least we know that some day we'll have it :)
