### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by CezarLuiz0** [tleunen/react-mdl#54]
How can I change the primary color?

Thanks!

**Comment by tleunen** [comment]
If you're using the custom files we provide (which fixes an issue with the Layout component), that's unfortunately not possible for now...
If you don't use the layout component, you can safely use the CSS files provided by the MDL team.

**Comment by CezarLuiz0** [comment]
As I thought...

What do you think to build the custom files with sass, less or anyone? Like Twitter Bootstrap http://getbootstrap.com/customize/ but more simple, just primary and accent color.

Can I change manually the colors using, I dont'n know, "cmd+f"? 

Thanks!

**Comment by faergeek** [comment]
I guess you can change colors and other variables using sass to compile material-design-lite and `@import` `_layout.scss` from `extra` folder instead of upstream like so (just copy [original](https://github.com/google/material-design-lite/blob/master/src/material-design-lite.scss) and change paths):

```sass
// Variables and mixins
@import "material-design-lite/src/variables";
...
@import "react-mdl/extra/layout";
...
@import "material-design-lite/src/grid/grid";
```

**Comment by slybridges** [comment]
@faergeek Yep, but I think you should add a tilde in front of the module in scss, like so:
```css
@import "~material-design-lite/src/variables";
```
Also the import of `layouts.scss` from `react-mdl` won't work directly because the file contain the following imports with relative paths: 
```css
@import "../variables";
@import "../mixins";
```

@tleunen maybe it would be good to change those two lines to:
```css
@import "~material-design-lite/src/variables";
@import "~material-design-lite/src/mixins";
```

So that we can make a direct import without changing that file locally?
```css
@import "~react-mdl/extra/layout";
```

**Comment by sontek** [comment]
@tleunen Why was this closed?

**Comment by tleunen** [comment]
Because @slybridges said using `~` would fix the issue and we now use it in our scss patch file

**Comment by sontek** [comment]
@tleunen ok, I was trying to figure out if what I'm doing is fine and saw this.  So far I've done:

```
// Variables and mixins
@import "./variables";
@import "~material-design-lite/src/variables";


@import "~material-design-lite/src/mixins";

// Resets and dependencies
@import "~material-design-lite/src/resets/resets";
@import "~material-design-lite/src/typography/typography";

// Components
@import "~material-design-lite/src/palette/palette";
@import "~material-design-lite/src/ripple/ripple";
@import "~material-design-lite/src/animation/animation";
@import "~material-design-lite/src/badge/badge";
@import "~material-design-lite/src/button/button";
@import "~material-design-lite/src/card/card";
@import "~material-design-lite/src/checkbox/checkbox";
@import "~material-design-lite/src/data-table/data-table";
@import "~material-design-lite/src/dialog/dialog";
@import "~material-design-lite/src/footer/mega_footer";
@import "~material-design-lite/src/footer/mini_footer";
@import "~material-design-lite/src/icon-toggle/icon-toggle";
@import "~material-design-lite/src/list/list";
@import "~material-design-lite/src/menu/menu";
@import "~material-design-lite/src/progress/progress";
@import "~material-design-lite/src/radio/radio";
@import "~material-design-lite/src/slider/slider";
@import "~material-design-lite/src/snackbar/snackbar";
@import "~material-design-lite/src/spinner/spinner";
@import "~material-design-lite/src/switch/switch";
@import "~material-design-lite/src/tabs/tabs";
@import "~material-design-lite/src/textfield/textfield";
@import "~material-design-lite/src/tooltip/tooltip";
@import "~material-design-lite/src/shadow/shadow";
@import "~material-design-lite/src/grid/grid";

/* Fixes small screen layout for navbar */
@import "~react-mdl/extra/layout";
```

which seems to render everything but the hamburger icon

**Comment by sontek** [comment]
The `./variables` is my variable that sets the colors I need.   As a a suggestion, I love the way `material-ui` does this with a ThemeComponent:

http://www.material-ui.com/#/customization/themes

So it might be worth adding that to this project.

**Comment by tleunen** [comment]
Yes, I'm also very interested in improving the way we can customize the components. With our v2, I wanted to remove all the direct css dependency to have each component have their own css dependency (using css-modules or something similar). But I didn't get the time right now to investigate all this.

Then with a root "ThemeProvider", we could indeed let the user choose the main theme color he want to use, probably based on this: https://getmdl.io/customize/index.html

Feel free to jump in, try a few things and propose something in a PR ;)

**Comment by reygiecacho** [comment]
how can i change the button color?

**Comment by ianbaker615** [comment]
In case anyone else is curious, I fixed this issue by adding `!important` to the end of the color declaration ie

```
.header-color {
  background-color: black !important;
  opacity: 0.8;
}
```
