### ISSUE TITLE
LinkState and valueLink bug

### ISSUE THREAD

**Issue by CezarLuiz0** [tleunen/react-mdl#55]
When I use the linkState mixin:

Uncaught Error: Invariant Violation: Cannot provide a valueLink and a value or onChange event. If you want to use value or onChange, you probably don't want to use valueLink.

Any idea?

**Comment by tleunen** [comment]
If you're using `valueLink`, you can't provide `onChange` and `value`. The valueLink does the work for you.

**Comment by CezarLuiz0** [comment]
I'm not using `onChange` or `value`, I'm using `valueLink` and I get the error :/
