### ISSUE TITLE
Textfield with react-router cause "Invariant Violation" Error

### ISSUE THREAD

**Issue by eisneim** [tleunen/react-mdl#6]
a page contains Textfield and when hit a link change the route, it will throw this Error:
```
Uncaught Error: Invariant Violation: ReactMount: Root element ID differed from reactRootID.
```
the problem is in react's ReactMount.js: 631 findReactContainerForID(id)
```javascript
var reactRootID = ReactInstanceHandles.getReactRootIDFromNodeID(id);
 var container = containersByReactRootID[reactRootID];
 if ("production" !== process.env.NODE_ENV) {
      var rootElement = rootElementsByReactRootID[reactRootID];
      if (rootElement && rootElement.parentNode !== container) {
 /*
the problem is here:
container == <body>
rootElement === <div class="mdl-layout__container">
rootElement.parentNode === null, but why ???? it should be the <body>


*/

```

**Comment by tleunen** [comment]
I never experienced this error with the textfield component. Only with the layout.
And based on your log, it seems you're also using the layout component. (from react-mdl or not, it doesn't really matter I think). But it's causing some issues that I described here (https://github.com/google/material-design-lite/issues/1356). I submitted a fix but it cannot be merged before the next major version.

You can easily get my fix and build new js/css material files. I'm also thinking of providing them inside this repo until a proper fix is done in MDL.

**Comment by eisneim** [comment]
thanks so much!

**Comment by tleunen** [comment]
If you want to use the Layout component, I suggests you use my custom [material.js](https://github.com/tleunen/react-mdl/blob/master/demo/material.js) and [material.css](https://github.com/tleunen/react-mdl/blob/master/demo/material.css) files.

This is based on the latest version of MDL (1.0.4 when writing this post).

**Comment by eisneim** [comment]
thanks, i'm gonna try it
