### ISSUE TITLE
react 0.14.0-rc1, peerDependency issue

### ISSUE THREAD

**Issue by bfreis** [tleunen/react-mdl#62]
Hi,

I have "react": "0.14.0-rc1" in my project's package.json. When I try to install react-mdl, I get an error because of the peerDependency on react.

    npm ERR! peerinvalid The package react@0.14.0-rc1 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-mdl@0.14.0 wants react@0.13.x || ^0.14.0

Thanks

**Comment by faergeek** [comment]
See #59
If you use npm@3 there should be no problems with it.

**Comment by bfreis** [comment]
Sergey, thanks for the quick response!

I got it to work now, after upgrading to npm@3.3.6. The error became just a warning now:

    npm WARN EPEERINVALID react-mdl@0.14.0 requires a peer of react@0.13.x || ^0.14.0 but none was installed.

At least it did install react-mdl!

Thanks!
Bruno
