### ISSUE TITLE
Can't include demo/material.js from npm installed packaged

### ISSUE THREAD

**Issue by bvleur** [tleunen/react-mdl#9]
Per the current README projects integrating react-mdl should use the material.js from the  `/demo/` but it is excluded using `.npmignore`.

It would be nice if the customized `material.js` is made available in the npm package. Maybe in a different folder?

**Comment by tleunen** [comment]
I didn't build the minified files tho. Will think about it for the next release of MDL ;)

**Comment by cjk** [comment]
@bvleur The files are found in the /extra folder. You should be able to integrate them using Webpack et.al. or just copy / symlink them to a local assets-folder and add a script-tag.
But yeah, a minified version for the latter case would be nice.
