### ISSUE TITLE
Does Header really need HeaderRow or HeaderTabs inside?

### ISSUE THREAD

**Issue by kretz** [tleunen/react-mdl#94]
I'm trying to implement http://www.getmdl.io/templates/dashboard/index.html with the `react-mdl`module.

All of it except the header part of the drawer is possible to do. The top part of the drawer looks like this; 

```html
...
<header class="demo-drawer-header">
  <img src="images/user.jpg" class="demo-avatar">
  <div class="demo-avatar-dropdown">
    <span>hello@example.com</span>
    <div class="mdl-layout-spacer"></div>
    <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" data-upgraded=",MaterialButton,MaterialRipple">
      <i class="material-icons" role="presentation">arrow_drop_down</i>
      <span class="visuallyhidden">Accounts</span>
      <span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span>
    </button>
    <div class="mdl-menu__container is-upgraded">
    ...stripped...
    </div>
  </div>
</header>
...
```

If I try to do this with the `<Header>` component, it required one of the children to be a `<HeaderTabs>` or `<HeaderRow>` or it will just wrap it with a `<HeaderRow>`. 

I would like to avoid that wrapping. Can that be done?

**Comment by tleunen** [comment]
You can put whatever you want inside the `Drawer` component. So you can add your custom header if you want instead of using the `Header` component. (Which doesn't seem to be the case in this mdl example anyway).

**Comment by szimek** [comment]
@tleunen Hey, I've got similar question. I'd like to add a back button to the header:
```html
<header class="mdl-layout__header">
  <button class="mdl-layout-icon mdl-button mdl-js-button mdl-button--icon">
    <i class="material-icons">arrow_back</i>
  </button>    
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title">Some title</span>
    <div class="mdl-layout-spacer"></div>
  </div>
</header>
```
I guess it's not possible with the current `Header` component? I can always use plain HTML, just asking :)

**Comment by tleunen** [comment]
Everything you put in a `<Header>` will be wrap inside a `HeaderRow`, unless it's already a row, or a tab.
So with the current implementation, you cannot achieve exactly the same thing as what you describe, but you can have something quite similar I think using this:
```jsx
const customTitle = <div><IconButton name="arrow_back" /> Some title</div>;
<Header title={customTitle} />
```

**Comment by szimek** [comment]
This works:
```html
<header className="mdl-layout__header is-casting-shadow">
  <IconButton name="arrow_back" className="mdl-layout-icon" />
  <HeaderRow title={title}>
    ...     
  </HeaderRow>
</header>
```
@tleunen Thanks for this awesome library!
